/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.moderntech.views;

import java.sql.SQLException;
import lk.ijse.moderntech.controler.AddCustomer_quickController;
import lk.ijse.moderntech.model.CustomerModel;

/**
 *
 * @author Shamal
 */
public class AddCustomer_quick2 extends javax.swing.JDialog {

    int mouseX;
    int mouseY;
    AddRepair rep;
    String id;
    String name;

    /**
     * Creates new form AddCustomer_quick2
     */
    public AddCustomer_quick2(java.awt.Frame parent, boolean modal, AddRepair rep) {
        super(parent, modal);
        initComponents();
        this.setModal(true);
        this.setAlwaysOnTop(true);
        this.setModalityType(ModalityType.APPLICATION_MODAL);
        loadCustomerID();
        this.rep = rep;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBack = new javax.swing.JPanel();
        lblCustomerid = new javax.swing.JLabel();
        txtCustomerid = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblAdress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        lblContact = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        btnClear = new keeptoo.KButton();
        btnSave = new keeptoo.KButton();
        lblClose = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        pnlBack.setBackground(new java.awt.Color(220, 220, 220));
        pnlBack.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlBackMouseDragged(evt);
            }
        });
        pnlBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlBackMousePressed(evt);
            }
        });
        pnlBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCustomerid.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblCustomerid.setText("Customer ID :");
        pnlBack.add(lblCustomerid, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        txtCustomerid.setBackground(new java.awt.Color(220, 220, 220));
        txtCustomerid.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        txtCustomerid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 120, 215)));
        txtCustomerid.setEnabled(false);
        pnlBack.add(txtCustomerid, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 320, -1));

        lblName.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblName.setText("Name :");
        pnlBack.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        txtName.setBackground(new java.awt.Color(220, 220, 220));
        txtName.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        txtName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 120, 215)));
        pnlBack.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 320, -1));

        lblAdress.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblAdress.setText("Address :");
        pnlBack.add(lblAdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        txtAddress.setBackground(new java.awt.Color(220, 220, 220));
        txtAddress.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        txtAddress.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 120, 215)));
        pnlBack.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 870, -1));

        lblContact.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblContact.setText("Contact no :");
        pnlBack.add(lblContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, -1, -1));

        txtContact.setBackground(new java.awt.Color(220, 220, 220));
        txtContact.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        txtContact.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 120, 215)));
        pnlBack.add(txtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 150, 330, -1));

        btnClear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 46, 50)));
        btnClear.setForeground(new java.awt.Color(255, 46, 50));
        btnClear.setText("Clear");
        btnClear.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        btnClear.setkAllowGradient(false);
        btnClear.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        btnClear.setkBorderRadius(0);
        btnClear.setkForeGround(new java.awt.Color(255, 46, 50));
        btnClear.setkHoverColor(new java.awt.Color(255, 46, 50));
        btnClear.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        pnlBack.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 350, -1, -1));

        btnSave.setBorder(null);
        btnSave.setText("Save");
        btnSave.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        btnSave.setkAllowGradient(false);
        btnSave.setkBackGroundColor(new java.awt.Color(0, 120, 215));
        btnSave.setkBorderRadius(0);
        btnSave.setkHoverColor(new java.awt.Color(0, 80, 143));
        btnSave.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        pnlBack.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 350, -1, -1));

        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/moderntech/img/icons8_cancel_25px.png"))); // NOI18N
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });
        pnlBack.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 0, 30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBack, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearAll();
        loadCustomerID();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        CustomerModel customer = new CustomerModel(
                txtCustomerid.getText(),
                txtName.getText(),
                txtContact.getText(),
                txtAddress.getText()
        );

        try {
            boolean saved = new AddCustomer_quickController().saveCustomer(customer);
            if (saved) {
                new InformationBox(new javax.swing.JFrame(), true, "Saved successfully.").setVisible(true);
                id = txtCustomerid.getText();
                name = txtName.getText();
                clearAll();
            } else {
                new InformationBox(new javax.swing.JFrame(), true, "Something went wrong, Tray again.").setVisible(true);
            }
        } catch (ClassNotFoundException ex) {
            new ErrorBox(new javax.swing.JFrame(), true, "Class not found exception").setVisible(true);
        } catch (SQLException ex) {
            new ErrorBox(new javax.swing.JFrame(), true, "Sql exception").setVisible(true);
        }
        loadCustomerID();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        if (id == null || name == null) {
            rep.cmbCustomerID.setSelectedItem("C0001");
            rep.txtCName.setText("Cash customer");
            this.dispose();
        } else {
            rep.cmbCustomerID.setSelectedItem(id);
            rep.txtCName.setText(name);
            this.dispose();
        }
    }//GEN-LAST:event_lblCloseMouseClicked

    private void pnlBackMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBackMouseDragged
        int X = evt.getXOnScreen();
        int Y = evt.getYOnScreen();

        this.setLocation(X - mouseX, Y - mouseY);
    }//GEN-LAST:event_pnlBackMouseDragged

    private void pnlBackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBackMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_pnlBackMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCustomer_quick2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCustomer_quick2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCustomer_quick2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCustomer_quick2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddCustomer_quick2 dialog = new AddCustomer_quick2(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btnClear;
    private keeptoo.KButton btnSave;
    private javax.swing.JLabel lblAdress;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblCustomerid;
    private javax.swing.JLabel lblName;
    private javax.swing.JPanel pnlBack;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtCustomerid;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

    private void clearAll() {
        txtCustomerid.setText("");
        txtName.setText("");
        txtContact.setText("");
        txtAddress.setText("");
    }

    private void loadCustomerID() {
        try {
            String id = new AddCustomer_quickController().getCustomerID();
            txtCustomerid.setText(id);
        } catch (ClassNotFoundException ex) {
            new ErrorBox(new javax.swing.JFrame(), true, "Class not found exception").setVisible(true);
        } catch (SQLException ex) {
            new ErrorBox(new javax.swing.JFrame(), true, "Sql exception").setVisible(true);
        }
    }
}
