/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.moderntech.views;

import java.awt.Color;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import lk.ijse.moderntech.controler.AddPartController;
import lk.ijse.moderntech.model.PartModel;

/**
 *
 * @author Shamal
 */
public class AddPart extends javax.swing.JInternalFrame {

    boolean state;

    public AddPart(boolean state) {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.state = state;
        setTheam();
        loadPartID();
        loadWarranty();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBack = new javax.swing.JPanel();
        txtPartID = new javax.swing.JTextField();
        lblComputerid = new javax.swing.JLabel();
        lblWarranty = new javax.swing.JLabel();
        cmbWarranty = new javax.swing.JComboBox<>();
        lblPartname = new javax.swing.JLabel();
        txtPartname = new javax.swing.JTextField();
        lblValue = new javax.swing.JLabel();
        txtValue = new javax.swing.JTextField();
        lblBrand = new javax.swing.JLabel();
        txtBrand = new javax.swing.JTextField();
        lblDescription = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        btnSave = new keeptoo.KButton();
        btnClear = new keeptoo.KButton();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(1310, 820));

        pnlBack.setBackground(new java.awt.Color(255, 255, 255));
        pnlBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPartID.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        txtPartID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 120, 215)));
        txtPartID.setEnabled(false);
        pnlBack.add(txtPartID, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 320, -1));

        lblComputerid.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblComputerid.setText("Part ID :");
        pnlBack.add(lblComputerid, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        lblWarranty.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblWarranty.setText("Warranty :");
        pnlBack.add(lblWarranty, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        cmbWarranty.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        cmbWarranty.setBorder(null);
        pnlBack.add(cmbWarranty, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 320, 40));

        lblPartname.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblPartname.setText("Part name :");
        pnlBack.add(lblPartname, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, -1, -1));

        txtPartname.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        txtPartname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 120, 215)));
        pnlBack.add(txtPartname, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 140, 320, -1));

        lblValue.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblValue.setText("Value :");
        pnlBack.add(lblValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        txtValue.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        txtValue.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 120, 215)));
        pnlBack.add(txtValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 320, -1));

        lblBrand.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblBrand.setText("Brand :");
        pnlBack.add(lblBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 210, -1, -1));

        txtBrand.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        txtBrand.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 120, 215)));
        pnlBack.add(txtBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 210, 320, -1));

        lblDescription.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblDescription.setText("Description :");
        pnlBack.add(lblDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, -1));

        txtDescription.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        txtDescription.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 120, 215)));
        pnlBack.add(txtDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 870, -1));

        btnSave.setBorder(null);
        btnSave.setText("Save");
        btnSave.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        btnSave.setkAllowGradient(false);
        btnSave.setkBackGroundColor(new java.awt.Color(0, 120, 215));
        btnSave.setkBorderRadius(0);
        btnSave.setkHoverColor(new java.awt.Color(0, 80, 143));
        btnSave.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        pnlBack.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 360, -1, -1));

        btnClear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 46, 50)));
        btnClear.setForeground(new java.awt.Color(255, 46, 50));
        btnClear.setText("Clear");
        btnClear.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        btnClear.setkAllowGradient(false);
        btnClear.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        btnClear.setkBorderRadius(0);
        btnClear.setkForeGround(new java.awt.Color(255, 46, 50));
        btnClear.setkHoverColor(new java.awt.Color(255, 46, 50));
        btnClear.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        pnlBack.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 360, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearAll();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            PartModel part = new PartModel(
                    txtPartID.getText(),
                    cmbWarranty.getSelectedItem().toString(),
                    txtPartname.getText(),
                    txtValue.getText(),
                    txtBrand.getText(),
                    txtDescription.getText()
            );
            boolean saved = new AddPartController().savePart(part);
            if(saved){
                new InformationBox(new javax.swing.JFrame(), true, "Saved successfully.").setVisible(true);
            }else{
                new InformationBox(new javax.swing.JFrame(), true, "Something went wrong, try again.").setVisible(true);
            }
            
        } catch (ClassNotFoundException ex) {
            new ErrorBox(new javax.swing.JFrame(), true, "Class not found exception").setVisible(true);
        } catch (SQLException ex) {
            new ErrorBox(new javax.swing.JFrame(), true, "Sql exception").setVisible(true);
        }
        loadPartID();
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btnClear;
    private keeptoo.KButton btnSave;
    private javax.swing.JComboBox<String> cmbWarranty;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblComputerid;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblPartname;
    private javax.swing.JLabel lblValue;
    private javax.swing.JLabel lblWarranty;
    private javax.swing.JPanel pnlBack;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtPartID;
    private javax.swing.JTextField txtPartname;
    private javax.swing.JTextField txtValue;
    // End of variables declaration//GEN-END:variables

    private void setTheam() {
        if (state) {
            pnlBack.setBackground(Color.BLACK);
            lblBrand.setForeground(Color.WHITE);
            lblComputerid.setForeground(Color.WHITE);
            lblDescription.setForeground(Color.WHITE);
            lblPartname.setForeground(Color.WHITE);
            lblValue.setForeground(Color.WHITE);
            lblWarranty.setForeground(Color.WHITE);
            cmbWarranty.setForeground(Color.WHITE);
            cmbWarranty.setBackground(Color.BLACK);
            txtBrand.setForeground(Color.WHITE);
            txtPartID.setForeground(Color.WHITE);
            txtDescription.setForeground(Color.WHITE);
            txtPartname.setForeground(Color.WHITE);
            txtValue.setForeground(Color.WHITE);
            txtBrand.setBackground(Color.BLACK);
            txtPartID.setBackground(Color.BLACK);
            txtDescription.setBackground(Color.BLACK);
            txtPartname.setBackground(Color.BLACK);
            txtValue.setBackground(Color.BLACK);
        } else {

        }
    }

    private void loadPartID() {
        try {
            String id = new AddPartController().getPartID();
            txtPartID.setText(id);
        } catch (ClassNotFoundException ex) {
            new ErrorBox(new javax.swing.JFrame(), true, "Class not found exception").setVisible(true);
        } catch (SQLException ex) {
            new ErrorBox(new javax.swing.JFrame(), true, "Sql exception").setVisible(true);
        }
    }

    private void loadWarranty() {
        try {
            List<String> list = new AddPartController().getWarranty();
            for (String string : list) {
                cmbWarranty.addItem(string);
            }
        } catch (ClassNotFoundException ex) {
            new ErrorBox(new javax.swing.JFrame(), true, "Class not found exception").setVisible(true);
        } catch (SQLException ex) {
            new ErrorBox(new javax.swing.JFrame(), true, "Sql exception").setVisible(true);
        }
    }

    private void clearAll() {
        txtBrand.setText("");
        txtDescription.setText("");
        txtPartID.setText("");
        txtPartname.setText("");
        txtValue.setText("");
        cmbWarranty.setSelectedIndex(0);
    }
}
