/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.moderntech.views;

import java.awt.Color;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import lk.ijse.moderntech.controler.AddStockController;
import lk.ijse.moderntech.model.SSModel;
import lk.ijse.moderntech.model.StockModel;

/**
 *
 * @author Shamal
 */
public class AddStock extends javax.swing.JInternalFrame {

    boolean state;

    public AddStock(boolean state) {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.state = state;
        setTheam();
        loadStockID();
        loadSupplierID();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBack = new javax.swing.JPanel();
        lblStockid = new javax.swing.JLabel();
        txtStockid = new javax.swing.JTextField();
        lblItemid = new javax.swing.JLabel();
        txtItemid = new javax.swing.JTextField();
        lblQty = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        lblSupplierid = new javax.swing.JLabel();
        txtBuyingprice = new javax.swing.JTextField();
        lblProfitpresentage = new javax.swing.JLabel();
        txtProfitpresentage = new javax.swing.JTextField();
        lblSellingprice = new javax.swing.JLabel();
        txtSellingprice = new javax.swing.JTextField();
        lblBuyingprice = new javax.swing.JLabel();
        cmbSupplierid = new javax.swing.JComboBox<>();
        btnSave = new keeptoo.KButton();
        btnClear = new keeptoo.KButton();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(1310, 820));

        pnlBack.setBackground(new java.awt.Color(255, 255, 255));
        pnlBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblStockid.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblStockid.setText("Stock ID :");
        pnlBack.add(lblStockid, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));

        txtStockid.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        txtStockid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 120, 215)));
        txtStockid.setEnabled(false);
        pnlBack.add(txtStockid, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 320, -1));

        lblItemid.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblItemid.setText("Item ID :");
        pnlBack.add(lblItemid, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 70, -1));

        txtItemid.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        txtItemid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 120, 215)));
        pnlBack.add(txtItemid, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 320, -1));

        lblQty.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblQty.setText("QTY :");
        pnlBack.add(lblQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 140, 50, -1));

        txtQty.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        txtQty.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 120, 215)));
        txtQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQtyKeyReleased(evt);
            }
        });
        pnlBack.add(txtQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 140, 320, -1));

        lblSupplierid.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblSupplierid.setText("Supplier ID :");
        pnlBack.add(lblSupplierid, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 110, -1));

        txtBuyingprice.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        txtBuyingprice.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 120, 215)));
        pnlBack.add(txtBuyingprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 320, -1));

        lblProfitpresentage.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblProfitpresentage.setText("Profit precentage :");
        pnlBack.add(lblProfitpresentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, 180, -1));

        txtProfitpresentage.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        txtProfitpresentage.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 120, 215)));
        txtProfitpresentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfitpresentageActionPerformed(evt);
            }
        });
        txtProfitpresentage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProfitpresentageKeyReleased(evt);
            }
        });
        pnlBack.add(txtProfitpresentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 290, 320, -1));

        lblSellingprice.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblSellingprice.setText("Selling price :");
        pnlBack.add(lblSellingprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 120, -1));

        txtSellingprice.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        txtSellingprice.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 120, 215)));
        pnlBack.add(txtSellingprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 320, -1));

        lblBuyingprice.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblBuyingprice.setText("Buying price :");
        pnlBack.add(lblBuyingprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 120, -1));

        cmbSupplierid.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        pnlBack.add(cmbSupplierid, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 310, -1));

        btnSave.setBorder(null);
        btnSave.setText("Save");
        btnSave.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        btnSave.setkAllowGradient(false);
        btnSave.setkBackGroundColor(new java.awt.Color(0, 120, 215));
        btnSave.setkBorderRadius(0);
        btnSave.setkHoverColor(new java.awt.Color(0, 80, 143));
        btnSave.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        pnlBack.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 460, -1, -1));

        btnClear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 46, 50)));
        btnClear.setForeground(new java.awt.Color(255, 46, 50));
        btnClear.setText("Clear");
        btnClear.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        btnClear.setkAllowGradient(false);
        btnClear.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        btnClear.setkBorderRadius(0);
        btnClear.setkForeGround(new java.awt.Color(255, 46, 50));
        btnClear.setkHoverColor(new java.awt.Color(255, 46, 50));
        btnClear.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        pnlBack.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 460, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        StockModel stock = new StockModel();
        if (txtItemid.getText().substring(0, 1).equals("P")) {
            stock.setPartID(txtItemid.getText());
        } else if (txtItemid.getText().substring(0, 1).equals("C")) {
            stock.setComputerID(txtItemid.getText());
        }
        stock.setStockID(txtStockid.getText());
        stock.setQTYonhand(txtQty.getText());
        stock.setBuyingPrice(txtBuyingprice.getText());
        stock.setProfitPrecentage(txtProfitpresentage.getText());
        stock.setSellingPricel(txtSellingprice.getText());

        SSModel ss = new SSModel(txtStockid.getText(), cmbSupplierid.getSelectedItem().toString());

        try {
            boolean saved = new AddStockController().saveStock(stock, ss);
            if (saved) {
                new InformationBox(new javax.swing.JFrame(), true, "Saved successfully.").setVisible(true);
            } else {
                new InformationBox(new javax.swing.JFrame(), true, "Something went wrong, Try again.").setVisible(true);
            }
        } catch (ClassNotFoundException ex) {
            new ErrorBox(new javax.swing.JFrame(), true, "Class not found exception").setVisible(true);
        } catch (SQLException ex) {
            new ErrorBox(new javax.swing.JFrame(), true, "Sql exception").setVisible(true);
        }
        loadStockID();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearAll();
        loadSupplierID();
        loadStockID();
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtProfitpresentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfitpresentageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfitpresentageActionPerformed

    private void txtProfitpresentageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProfitpresentageKeyReleased
        double buyingPrice = Double.valueOf(txtBuyingprice.getText());
        double profitprecentage = Double.valueOf(txtProfitpresentage.getText());
        profitprecentage += 100;
        double sellingprice = (profitprecentage / 100) * buyingPrice;
        sellingprice = round(sellingprice, 2);
        txtSellingprice.setText(sellingprice+"0");
    }//GEN-LAST:event_txtProfitpresentageKeyReleased

    private void txtQtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyKeyReleased
        if(!txtQty.getText().matches("[0-9]*")){
            new InformationBox(new javax.swing.JFrame(), true, "Please only enter numbers.").setVisible(true);
            txtQty.setText(txtQty.getText().substring(0, txtQty.getText().length()-1));
        }
    }//GEN-LAST:event_txtQtyKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btnClear;
    private keeptoo.KButton btnSave;
    private javax.swing.JComboBox<String> cmbSupplierid;
    private javax.swing.JLabel lblBuyingprice;
    private javax.swing.JLabel lblItemid;
    private javax.swing.JLabel lblProfitpresentage;
    private javax.swing.JLabel lblQty;
    private javax.swing.JLabel lblSellingprice;
    private javax.swing.JLabel lblStockid;
    private javax.swing.JLabel lblSupplierid;
    private javax.swing.JPanel pnlBack;
    private javax.swing.JTextField txtBuyingprice;
    private javax.swing.JTextField txtItemid;
    private javax.swing.JTextField txtProfitpresentage;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtSellingprice;
    private javax.swing.JTextField txtStockid;
    // End of variables declaration//GEN-END:variables

    private void setTheam() {
        if (state) {
            pnlBack.setBackground(Color.BLACK);
            lblBuyingprice.setForeground(Color.WHITE);
            lblItemid.setForeground(Color.WHITE);
            lblProfitpresentage.setForeground(Color.WHITE);
            lblQty.setForeground(Color.WHITE);
            lblSellingprice.setForeground(Color.WHITE);
            lblStockid.setForeground(Color.WHITE);
            lblSupplierid.setForeground(Color.WHITE);
            cmbSupplierid.setForeground(Color.white);
            cmbSupplierid.setBackground(Color.BLACK);
            txtBuyingprice.setForeground(Color.WHITE);
            txtItemid.setForeground(Color.WHITE);
            txtProfitpresentage.setForeground(Color.WHITE);
            txtQty.setForeground(Color.WHITE);
            txtSellingprice.setForeground(Color.WHITE);
            txtStockid.setForeground(Color.WHITE);
            txtBuyingprice.setBackground(Color.BLACK);
            txtItemid.setBackground(Color.BLACK);
            txtProfitpresentage.setBackground(Color.BLACK);
            txtQty.setBackground(Color.BLACK);
            txtSellingprice.setBackground(Color.BLACK);
            txtStockid.setBackground(Color.BLACK);
        } else {
        }
    }

    private void loadStockID() {
        try {
            String id = new AddStockController().getStockID();
            txtStockid.setText(id);
        } catch (ClassNotFoundException ex) {
            new ErrorBox(new javax.swing.JFrame(), true, "Class not found exception").setVisible(true);
        } catch (SQLException ex) {
            new ErrorBox(new javax.swing.JFrame(), true, "Sql exception").setVisible(true);
        }
    }

    private void loadSupplierID() {
        try {
            List<String> list = new AddStockController().getSupplier();
            for (String string : list) {
                cmbSupplierid.addItem(string);
            }
        } catch (ClassNotFoundException ex) {
            new ErrorBox(new javax.swing.JFrame(), true, "Class not found exception").setVisible(true);
        } catch (SQLException ex) {
            new ErrorBox(new javax.swing.JFrame(), true, "Sql exception").setVisible(true);
        }
    }

    private void clearAll() {
        txtBuyingprice.setText("");
        txtItemid.setText("");
        txtProfitpresentage.setText("");
        txtQty.setText("");
        txtSellingprice.setText("");
        txtStockid.setText("");
        cmbSupplierid.setSelectedIndex(0);
    }

    public static double round(double value, int places) {
        if (places < 0) {
            throw new IllegalArgumentException();
        }

        BigDecimal bd = BigDecimal.valueOf(value);
        bd = bd.setScale(places, RoundingMode.HALF_UP);
        return bd.doubleValue();
    }
}
