/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.moderntech.views;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import lk.ijse.moderntech.controler.CustomIncomeController;

/**
 *
 * @author Shamal
 */
public class CustomIncome extends javax.swing.JInternalFrame {

    boolean state;

    /**
     * Creates new form CustomIncome
     */
    public CustomIncome(boolean state) {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.state = state;
        setTheam();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBack = new javax.swing.JPanel();
        lblEnddate = new javax.swing.JLabel();
        lblStartingdate = new javax.swing.JLabel();
        txtEnddate = new javax.swing.JTextField();
        txtStartingdate = new javax.swing.JTextField();
        btnGenerate = new keeptoo.KButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblOrderincome = new javax.swing.JLabel();
        lblOc = new javax.swing.JLabel();
        lblOrdercount = new javax.swing.JLabel();
        lnlOi = new javax.swing.JLabel();
        lblTotalorderincome = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblRepairincome = new javax.swing.JLabel();
        lblRepaircount = new javax.swing.JLabel();
        lblRc = new javax.swing.JLabel();
        lblRi = new javax.swing.JLabel();
        lblTotalrepairincome = new javax.swing.JLabel();
        lblTot = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lblTotal = new javax.swing.JLabel();
        lblT = new javax.swing.JLabel();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(1300, 634));

        pnlBack.setBackground(new java.awt.Color(255, 255, 255));
        pnlBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEnddate.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblEnddate.setText("End date :");
        pnlBack.add(lblEnddate, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, -1, -1));

        lblStartingdate.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblStartingdate.setText("Starting date :");
        pnlBack.add(lblStartingdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        txtEnddate.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        txtEnddate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 120, 215)));
        pnlBack.add(txtEnddate, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, 330, -1));

        txtStartingdate.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        txtStartingdate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 120, 215)));
        pnlBack.add(txtStartingdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 330, -1));

        btnGenerate.setText("Generate");
        btnGenerate.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        btnGenerate.setkAllowGradient(false);
        btnGenerate.setkBackGroundColor(new java.awt.Color(102, 152, 245));
        btnGenerate.setkBorderRadius(0);
        btnGenerate.setkHoverColor(new java.awt.Color(8, 122, 217));
        btnGenerate.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });
        pnlBack.add(btnGenerate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 20, 110, -1));
        pnlBack.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 1260, 10));

        lblOrderincome.setFont(new java.awt.Font("Poppins", 0, 36)); // NOI18N
        lblOrderincome.setText("Order Income");
        pnlBack.add(lblOrderincome, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, -1, -1));

        lblOc.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblOc.setText("Order count :");
        pnlBack.add(lblOc, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 120, -1));

        lblOrdercount.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblOrdercount.setText("count");
        pnlBack.add(lblOrdercount, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));

        lnlOi.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lnlOi.setText("Total income :");
        pnlBack.add(lnlOi, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        lblTotalorderincome.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblTotalorderincome.setText("income");
        pnlBack.add(lblTotalorderincome, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));
        pnlBack.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 1290, 10));

        lblRepairincome.setFont(new java.awt.Font("Poppins", 0, 36)); // NOI18N
        lblRepairincome.setText("Repair income");
        pnlBack.add(lblRepairincome, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, -1, -1));

        lblRepaircount.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblRepaircount.setText("count");
        pnlBack.add(lblRepaircount, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, -1, -1));

        lblRc.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblRc.setText("Repair count :");
        pnlBack.add(lblRc, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        lblRi.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblRi.setText("Total income :");
        pnlBack.add(lblRi, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, -1));

        lblTotalrepairincome.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblTotalrepairincome.setText("income");
        pnlBack.add(lblTotalrepairincome, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, -1, -1));

        lblTot.setFont(new java.awt.Font("Poppins", 0, 36)); // NOI18N
        lblTot.setText("Total");
        pnlBack.add(lblTot, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 480, -1, -1));
        pnlBack.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 1290, 10));

        lblTotal.setBackground(new java.awt.Color(153, 255, 153));
        lblTotal.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        lblTotal.setText("total");
        pnlBack.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 570, -1, -1));

        lblT.setBackground(new java.awt.Color(153, 255, 153));
        lblT.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        lblT.setText("Total :");
        pnlBack.add(lblT, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 570, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        if (txtStartingdate.getText().trim().length() > 0 && txtEnddate.getText().trim().length() > 0) {
            try {
                List<String> list = new CustomIncomeController().getOrderDetail(txtStartingdate.getText(), txtEnddate.getText());
                if (list != null) {
                    lblOrdercount.setText(list.get(0));
                    lblTotalorderincome.setText(list.get(1));
                } else {
                    lblOrdercount.setText("0");
                    lblTotalorderincome.setText("0.00");
                }

                List<String> rep = new CustomIncomeController().getRepairDetail(txtStartingdate.getText(), txtEnddate.getText());
                if (rep != null) {
                    lblRepaircount.setText(rep.get(0));
                    lblTotalrepairincome.setText(rep.get(1));
                } else {
                    lblRepaircount.setText("0");
                    lblTotalrepairincome.setText("0.00");
                }

                if (lblOrdercount.getText().equals("0") && lblRepaircount.getText().equals("0")) {
                    lblTotal.setText("0.00");
                } else if (lblOrdercount.getText().equals("0")) {
                    lblTotal.setText(lblTotalrepairincome.getText());
                } else if (lblRepaircount.getText().equals("0")) {
                    lblTotal.setText(lblTotalorderincome.getText());
                } else if (!(lblOrdercount.getText().equals("0") && lblRepaircount.getText().equals("0"))) {
                    lblTotal.setText(Double.valueOf(lblTotalorderincome.getText()) + Double.valueOf(lblTotalrepairincome.getText()) + "0");
                }

            } catch (ClassNotFoundException ex) {
                new ErrorBox(new javax.swing.JFrame(), true, "Class not found exception").setVisible(true);
            } catch (SQLException ex) {
                new ErrorBox(new javax.swing.JFrame(), true, "Sql exception").setVisible(true);
            }
        } else {
            new InformationBox(new javax.swing.JFrame(), true, "Enter both dates.").setVisible(true);
        }
    }//GEN-LAST:event_btnGenerateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btnGenerate;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblEnddate;
    private javax.swing.JLabel lblOc;
    private javax.swing.JLabel lblOrdercount;
    private javax.swing.JLabel lblOrderincome;
    private javax.swing.JLabel lblRc;
    private javax.swing.JLabel lblRepaircount;
    private javax.swing.JLabel lblRepairincome;
    private javax.swing.JLabel lblRi;
    private javax.swing.JLabel lblStartingdate;
    private javax.swing.JLabel lblT;
    private javax.swing.JLabel lblTot;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalorderincome;
    private javax.swing.JLabel lblTotalrepairincome;
    private javax.swing.JLabel lnlOi;
    private javax.swing.JPanel pnlBack;
    private javax.swing.JTextField txtEnddate;
    private javax.swing.JTextField txtStartingdate;
    // End of variables declaration//GEN-END:variables

    private void setTheam() {
        if (state) {

        } else {

        }
    }
}
