/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.moderntech.views;

import java.awt.Color;

/**
 *
 * @author Shamal
 */
public class EmployeeMain extends javax.swing.JInternalFrame {

    Main main;
    boolean state;

    /**
     * Creates new form BillMain
     */
    public EmployeeMain(Main main, boolean state) {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.main = main;
        setTheme(state);
        this.state = state;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLeft = new javax.swing.JPanel();
        btnBack = new keeptoo.KButton();
        btnLogindetail = new keeptoo.KButton();
        btnAddUser = new keeptoo.KButton();
        btnUpdateUser = new keeptoo.KButton();
        btnDeleteuser = new keeptoo.KButton();
        pnlCenter = new javax.swing.JPanel();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(1600, 820));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLeft.setBackground(new java.awt.Color(230, 230, 230));
        pnlLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setBorder(null);
        btnBack.setForeground(new java.awt.Color(51, 51, 51));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/moderntech/img/icons8_left_arrow_30px.png"))); // NOI18N
        btnBack.setAlignmentY(0.0F);
        btnBack.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        btnBack.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnBack.setIconTextGap(30);
        btnBack.setkAllowGradient(false);
        btnBack.setkAllowTab(true);
        btnBack.setkBackGroundColor(new java.awt.Color(230, 230, 230));
        btnBack.setkBorderRadius(0);
        btnBack.setkForeGround(new java.awt.Color(51, 51, 51));
        btnBack.setkHoverColor(new java.awt.Color(212, 212, 212));
        btnBack.setkSelectedColor(new java.awt.Color(102, 102, 102));
        btnBack.setkStartColor(new java.awt.Color(255, 102, 102));
        btnBack.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        pnlLeft.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 60));

        btnLogindetail.setBorder(null);
        btnLogindetail.setForeground(new java.awt.Color(0, 0, 0));
        btnLogindetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/moderntech/img/icons8_Update_Left_Rotation_30px.png"))); // NOI18N
        btnLogindetail.setText("Update Login");
        btnLogindetail.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnLogindetail.setIconTextGap(20);
        btnLogindetail.setkAllowGradient(false);
        btnLogindetail.setkAllowTab(true);
        btnLogindetail.setkBackGroundColor(new java.awt.Color(230, 230, 230));
        btnLogindetail.setkBorderRadius(0);
        btnLogindetail.setkForeGround(new java.awt.Color(0, 0, 0));
        btnLogindetail.setkHoverColor(new java.awt.Color(212, 212, 212));
        btnLogindetail.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btnLogindetail.setkIndicatorColor(new java.awt.Color(0, 120, 215));
        btnLogindetail.setkIndicatorThickness(5);
        btnLogindetail.setkSelectedColor(new java.awt.Color(200, 200, 200));
        btnLogindetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogindetailActionPerformed(evt);
            }
        });
        pnlLeft.add(btnLogindetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, 290, 70));

        btnAddUser.setBorder(null);
        btnAddUser.setForeground(new java.awt.Color(0, 0, 0));
        btnAddUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/moderntech/img/icons8_add_30px.png"))); // NOI18N
        btnAddUser.setText("Add user");
        btnAddUser.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAddUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAddUser.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnAddUser.setIconTextGap(20);
        btnAddUser.setkAllowGradient(false);
        btnAddUser.setkAllowTab(true);
        btnAddUser.setkBackGroundColor(new java.awt.Color(230, 230, 230));
        btnAddUser.setkBorderRadius(0);
        btnAddUser.setkForeGround(new java.awt.Color(0, 0, 0));
        btnAddUser.setkHoverColor(new java.awt.Color(212, 212, 212));
        btnAddUser.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btnAddUser.setkIndicatorColor(new java.awt.Color(0, 120, 215));
        btnAddUser.setkIndicatorThickness(5);
        btnAddUser.setkSelectedColor(new java.awt.Color(200, 200, 200));
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });
        pnlLeft.add(btnAddUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 290, 70));

        btnUpdateUser.setBorder(null);
        btnUpdateUser.setForeground(new java.awt.Color(0, 0, 0));
        btnUpdateUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/moderntech/img/icons8_Update_Left_Rotation_30px.png"))); // NOI18N
        btnUpdateUser.setText("Update user");
        btnUpdateUser.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnUpdateUser.setIconTextGap(20);
        btnUpdateUser.setkAllowGradient(false);
        btnUpdateUser.setkAllowTab(true);
        btnUpdateUser.setkBackGroundColor(new java.awt.Color(230, 230, 230));
        btnUpdateUser.setkBorderRadius(0);
        btnUpdateUser.setkForeGround(new java.awt.Color(0, 0, 0));
        btnUpdateUser.setkHoverColor(new java.awt.Color(212, 212, 212));
        btnUpdateUser.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btnUpdateUser.setkIndicatorColor(new java.awt.Color(0, 120, 215));
        btnUpdateUser.setkIndicatorThickness(5);
        btnUpdateUser.setkSelectedColor(new java.awt.Color(200, 200, 200));
        btnUpdateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateUserActionPerformed(evt);
            }
        });
        pnlLeft.add(btnUpdateUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 290, 70));

        btnDeleteuser.setBorder(null);
        btnDeleteuser.setForeground(new java.awt.Color(0, 0, 0));
        btnDeleteuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/moderntech/img/icons8_delete_sign_30px.png"))); // NOI18N
        btnDeleteuser.setText("Delete user");
        btnDeleteuser.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnDeleteuser.setIconTextGap(20);
        btnDeleteuser.setkAllowGradient(false);
        btnDeleteuser.setkAllowTab(true);
        btnDeleteuser.setkBackGroundColor(new java.awt.Color(230, 230, 230));
        btnDeleteuser.setkBorderRadius(0);
        btnDeleteuser.setkForeGround(new java.awt.Color(0, 0, 0));
        btnDeleteuser.setkHoverColor(new java.awt.Color(212, 212, 212));
        btnDeleteuser.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btnDeleteuser.setkIndicatorColor(new java.awt.Color(0, 120, 215));
        btnDeleteuser.setkIndicatorThickness(5);
        btnDeleteuser.setkSelectedColor(new java.awt.Color(200, 200, 200));
        btnDeleteuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteuserActionPerformed(evt);
            }
        });
        pnlLeft.add(btnDeleteuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 290, 70));

        getContentPane().add(pnlLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 820));

        pnlCenter.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlCenterLayout = new javax.swing.GroupLayout(pnlCenter);
        pnlCenter.setLayout(pnlCenterLayout);
        pnlCenterLayout.setHorizontalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1310, Short.MAX_VALUE)
        );
        pnlCenterLayout.setVerticalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );

        getContentPane().add(pnlCenter, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 1310, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
        main.pnlMain.removeAll();
        main.pnlMain.repaint();
        main.pnlMain.add(new MainIcons(main, state)).setVisible(true);
        main.lblTitle.setText("Main");
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
        pnlCenter.removeAll();
        pnlCenter.repaint();
        pnlCenter.add(new AddEmployee(state)).setVisible(true);
    }//GEN-LAST:event_btnAddUserActionPerformed

    private void btnUpdateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateUserActionPerformed
        pnlCenter.removeAll();
        pnlCenter.repaint();
        pnlCenter.add(new UpdateEmployee(state)).setVisible(true);
    }//GEN-LAST:event_btnUpdateUserActionPerformed

    private void btnDeleteuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteuserActionPerformed
        pnlCenter.removeAll();
        pnlCenter.repaint();
        pnlCenter.add(new DeleteEmployee(state)).setVisible(true);
    }//GEN-LAST:event_btnDeleteuserActionPerformed

    private void btnLogindetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogindetailActionPerformed
        pnlCenter.removeAll();
        pnlCenter.repaint();
        pnlCenter.add(new UpdateLoginDetail(state, main)).setVisible(true);
    }//GEN-LAST:event_btnLogindetailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btnAddUser;
    private keeptoo.KButton btnBack;
    private keeptoo.KButton btnDeleteuser;
    private keeptoo.KButton btnLogindetail;
    private keeptoo.KButton btnUpdateUser;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlLeft;
    // End of variables declaration//GEN-END:variables

    private void setTheme(boolean state) {
        if (state) {
            pnlLeft.setBackground(new Color(99, 100, 100));
            pnlCenter.setBackground(Color.BLACK);

            btnBack.setkBackGroundColor(new Color(99, 100, 100));
            btnBack.setkForeGround(Color.WHITE);
            btnAddUser.setkBackGroundColor(new Color(99, 100, 100));
            btnAddUser.setForeground(Color.WHITE);
            btnAddUser.setkForeGround(Color.WHITE);
            btnUpdateUser.setkBackGroundColor(new Color(99, 100, 100));
            btnUpdateUser.setForeground(Color.WHITE);
            btnUpdateUser.setkForeGround(Color.WHITE);
            btnDeleteuser.setkBackGroundColor(new Color(99, 100, 100));
            btnDeleteuser.setForeground(Color.WHITE);
            btnDeleteuser.setkForeGround(Color.WHITE);
            btnLogindetail.setkBackGroundColor(new Color(99, 100, 100));
            btnLogindetail.setForeground(Color.WHITE);
            btnLogindetail.setkForeGround(Color.WHITE);
        } else {
            pnlLeft.setBackground(new Color(230, 230, 230));
            pnlCenter.setBackground(Color.WHITE);

            btnBack.setkBackGroundColor(new Color(230, 230, 230));
            btnBack.setkForeGround(Color.BLACK);
            btnAddUser.setkBackGroundColor(new Color(230, 230, 230));
            btnAddUser.setkForeGround(Color.BLACK);
            btnUpdateUser.setkBackGroundColor(new Color(230, 230, 230));
            btnUpdateUser.setkForeGround(Color.BLACK);
            btnDeleteuser.setkBackGroundColor(new Color(230, 230, 230));
            btnDeleteuser.setkForeGround(Color.BLACK);
        }
    }
}
