/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.moderntech.views;

/**
 *
 * @author Shamal
 */
public class ErrorBox extends javax.swing.JDialog {

    int mouseX;
    int mouseY;

    /**
     * Creates new form ErrorBox
     */
    public ErrorBox(java.awt.Frame parent, boolean modal, String message) {
        super(parent, modal);
        initComponents();
        this.setModal(true);
        this.setAlwaysOnTop(true);
        this.setModalityType(ModalityType.APPLICATION_MODAL);
        lblMessage.setText(message);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBack = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();
        lblInformation = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();
        btnOk = new keeptoo.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        pnlBack.setBackground(new java.awt.Color(220, 220, 220));
        pnlBack.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlBackMouseDragged(evt);
            }
        });
        pnlBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlBackMousePressed(evt);
            }
        });
        pnlBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/moderntech/img/icons8_cancel_25px.png"))); // NOI18N
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });
        pnlBack.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 0, -1, -1));

        lblInformation.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
        lblInformation.setText("Error!");
        pnlBack.add(lblInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, -1, -1));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/moderntech/img/icons8_delete_sign_400px.png"))); // NOI18N
        pnlBack.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, -80, 400, 400));

        lblMessage.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblMessage.setText("This is a sample message.");
        pnlBack.add(lblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));

        btnOk.setText("OK");
        btnOk.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
        btnOk.setkAllowGradient(false);
        btnOk.setkBackGroundColor(new java.awt.Color(216, 43, 43));
        btnOk.setkHoverColor(new java.awt.Color(144, 28, 28));
        btnOk.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        pnlBack.add(btnOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_lblCloseMouseClicked

    private void pnlBackMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBackMouseDragged
        int X = evt.getXOnScreen();
        int Y = evt.getYOnScreen();

        this.setLocation(X - mouseX, Y - mouseY);
    }//GEN-LAST:event_pnlBackMouseDragged

    private void pnlBackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBackMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_pnlBackMousePressed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ErrorBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ErrorBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ErrorBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ErrorBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ErrorBox dialog = new ErrorBox(new javax.swing.JFrame(), true, "This is a sample message.");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btnOk;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblInformation;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JPanel pnlBack;
    // End of variables declaration//GEN-END:variables
}
