/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.moderntech.views;

import java.awt.Color;

/**
 *
 * @author Shamal
 */
public class ItemsMain extends javax.swing.JInternalFrame {
    Main main;
    boolean state;
    /**
     * Creates new form BillMain
     */
    public ItemsMain(Main main, boolean state) {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.main = main;
        setTheme(state);
        this.state = state;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLeft = new javax.swing.JPanel();
        btnBack = new keeptoo.KButton();
        btnAddcomputer = new keeptoo.KButton();
        btnDeletecomputer = new keeptoo.KButton();
        btnWarranty = new keeptoo.KButton();
        btnUpdatepart = new keeptoo.KButton();
        btneletepart = new keeptoo.KButton();
        btnAddpart = new keeptoo.KButton();
        pnlCenter = new javax.swing.JPanel();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(1600, 820));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLeft.setBackground(new java.awt.Color(230, 230, 230));
        pnlLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setBorder(null);
        btnBack.setForeground(new java.awt.Color(51, 51, 51));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/moderntech/img/icons8_left_arrow_30px.png"))); // NOI18N
        btnBack.setAlignmentY(0.0F);
        btnBack.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        btnBack.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnBack.setIconTextGap(30);
        btnBack.setkAllowGradient(false);
        btnBack.setkAllowTab(true);
        btnBack.setkBackGroundColor(new java.awt.Color(230, 230, 230));
        btnBack.setkBorderRadius(0);
        btnBack.setkForeGround(new java.awt.Color(51, 51, 51));
        btnBack.setkHoverColor(new java.awt.Color(212, 212, 212));
        btnBack.setkSelectedColor(new java.awt.Color(102, 102, 102));
        btnBack.setkStartColor(new java.awt.Color(255, 102, 102));
        btnBack.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        pnlLeft.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 60));

        btnAddcomputer.setBackground(new java.awt.Color(230, 230, 230));
        btnAddcomputer.setBorder(null);
        btnAddcomputer.setForeground(new java.awt.Color(0, 0, 0));
        btnAddcomputer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/moderntech/img/icons8_add_30px.png"))); // NOI18N
        btnAddcomputer.setText("Add computer");
        btnAddcomputer.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAddcomputer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAddcomputer.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnAddcomputer.setIconTextGap(20);
        btnAddcomputer.setkAllowGradient(false);
        btnAddcomputer.setkAllowTab(true);
        btnAddcomputer.setkBackGroundColor(new java.awt.Color(230, 230, 230));
        btnAddcomputer.setkBorderRadius(0);
        btnAddcomputer.setkForeGround(new java.awt.Color(0, 0, 0));
        btnAddcomputer.setkHoverColor(new java.awt.Color(212, 212, 212));
        btnAddcomputer.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btnAddcomputer.setkIndicatorColor(new java.awt.Color(0, 120, 215));
        btnAddcomputer.setkIndicatorThickness(5);
        btnAddcomputer.setkSelectedColor(new java.awt.Color(200, 200, 200));
        btnAddcomputer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddcomputerActionPerformed(evt);
            }
        });
        pnlLeft.add(btnAddcomputer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 290, 70));

        btnDeletecomputer.setBackground(new java.awt.Color(230, 230, 230));
        btnDeletecomputer.setBorder(null);
        btnDeletecomputer.setForeground(new java.awt.Color(0, 0, 0));
        btnDeletecomputer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/moderntech/img/icons8_delete_sign_30px.png"))); // NOI18N
        btnDeletecomputer.setText("Delete computer");
        btnDeletecomputer.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnDeletecomputer.setIconTextGap(20);
        btnDeletecomputer.setkAllowGradient(false);
        btnDeletecomputer.setkAllowTab(true);
        btnDeletecomputer.setkBackGroundColor(new java.awt.Color(230, 230, 230));
        btnDeletecomputer.setkBorderRadius(0);
        btnDeletecomputer.setkForeGround(new java.awt.Color(0, 0, 0));
        btnDeletecomputer.setkHoverColor(new java.awt.Color(212, 212, 212));
        btnDeletecomputer.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btnDeletecomputer.setkIndicatorColor(new java.awt.Color(0, 120, 215));
        btnDeletecomputer.setkIndicatorThickness(5);
        btnDeletecomputer.setkSelectedColor(new java.awt.Color(200, 200, 200));
        btnDeletecomputer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletecomputerActionPerformed(evt);
            }
        });
        pnlLeft.add(btnDeletecomputer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 290, 70));

        btnWarranty.setBackground(new java.awt.Color(230, 230, 230));
        btnWarranty.setBorder(null);
        btnWarranty.setForeground(new java.awt.Color(0, 0, 0));
        btnWarranty.setText("Warranty");
        btnWarranty.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnWarranty.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnWarranty.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnWarranty.setIconTextGap(20);
        btnWarranty.setkAllowGradient(false);
        btnWarranty.setkAllowTab(true);
        btnWarranty.setkBackGroundColor(new java.awt.Color(230, 230, 230));
        btnWarranty.setkBorderRadius(0);
        btnWarranty.setkForeGround(new java.awt.Color(0, 0, 0));
        btnWarranty.setkHoverColor(new java.awt.Color(212, 212, 212));
        btnWarranty.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btnWarranty.setkIndicatorColor(new java.awt.Color(0, 120, 215));
        btnWarranty.setkIndicatorThickness(5);
        btnWarranty.setkSelectedColor(new java.awt.Color(200, 200, 200));
        btnWarranty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWarrantyActionPerformed(evt);
            }
        });
        pnlLeft.add(btnWarranty, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 720, 290, 70));

        btnUpdatepart.setBackground(new java.awt.Color(230, 230, 230));
        btnUpdatepart.setBorder(null);
        btnUpdatepart.setForeground(new java.awt.Color(0, 0, 0));
        btnUpdatepart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/moderntech/img/icons8_Update_Left_Rotation_30px.png"))); // NOI18N
        btnUpdatepart.setText("Update part");
        btnUpdatepart.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnUpdatepart.setIconTextGap(20);
        btnUpdatepart.setkAllowGradient(false);
        btnUpdatepart.setkAllowTab(true);
        btnUpdatepart.setkBackGroundColor(new java.awt.Color(230, 230, 230));
        btnUpdatepart.setkBorderRadius(0);
        btnUpdatepart.setkForeGround(new java.awt.Color(0, 0, 0));
        btnUpdatepart.setkHoverColor(new java.awt.Color(212, 212, 212));
        btnUpdatepart.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btnUpdatepart.setkIndicatorColor(new java.awt.Color(0, 120, 215));
        btnUpdatepart.setkIndicatorThickness(5);
        btnUpdatepart.setkSelectedColor(new java.awt.Color(200, 200, 200));
        btnUpdatepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatepartActionPerformed(evt);
            }
        });
        pnlLeft.add(btnUpdatepart, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 290, 70));

        btneletepart.setBackground(new java.awt.Color(230, 230, 230));
        btneletepart.setBorder(null);
        btneletepart.setForeground(new java.awt.Color(0, 0, 0));
        btneletepart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/moderntech/img/icons8_delete_sign_30px.png"))); // NOI18N
        btneletepart.setText("Delete part");
        btneletepart.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btneletepart.setIconTextGap(20);
        btneletepart.setkAllowGradient(false);
        btneletepart.setkAllowTab(true);
        btneletepart.setkBackGroundColor(new java.awt.Color(230, 230, 230));
        btneletepart.setkBorderRadius(0);
        btneletepart.setkForeGround(new java.awt.Color(0, 0, 0));
        btneletepart.setkHoverColor(new java.awt.Color(212, 212, 212));
        btneletepart.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btneletepart.setkIndicatorColor(new java.awt.Color(0, 120, 215));
        btneletepart.setkIndicatorThickness(5);
        btneletepart.setkSelectedColor(new java.awt.Color(200, 200, 200));
        btneletepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneletepartActionPerformed(evt);
            }
        });
        pnlLeft.add(btneletepart, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 290, 70));

        btnAddpart.setBackground(new java.awt.Color(230, 230, 230));
        btnAddpart.setBorder(null);
        btnAddpart.setForeground(new java.awt.Color(0, 0, 0));
        btnAddpart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/moderntech/img/icons8_add_30px.png"))); // NOI18N
        btnAddpart.setText("Add part");
        btnAddpart.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAddpart.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAddpart.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnAddpart.setIconTextGap(20);
        btnAddpart.setkAllowGradient(false);
        btnAddpart.setkAllowTab(true);
        btnAddpart.setkBackGroundColor(new java.awt.Color(230, 230, 230));
        btnAddpart.setkBorderRadius(0);
        btnAddpart.setkForeGround(new java.awt.Color(0, 0, 0));
        btnAddpart.setkHoverColor(new java.awt.Color(212, 212, 212));
        btnAddpart.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btnAddpart.setkIndicatorColor(new java.awt.Color(0, 120, 215));
        btnAddpart.setkIndicatorThickness(5);
        btnAddpart.setkSelectedColor(new java.awt.Color(200, 200, 200));
        btnAddpart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddpartActionPerformed(evt);
            }
        });
        pnlLeft.add(btnAddpart, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 290, 70));

        getContentPane().add(pnlLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 820));

        pnlCenter.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlCenterLayout = new javax.swing.GroupLayout(pnlCenter);
        pnlCenter.setLayout(pnlCenterLayout);
        pnlCenterLayout.setHorizontalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1310, Short.MAX_VALUE)
        );
        pnlCenterLayout.setVerticalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );

        getContentPane().add(pnlCenter, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 1310, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
        main.pnlMain.removeAll();
        main.pnlMain.repaint();
        main.pnlMain.add(new MainIcons(main, state)).setVisible(true);
        main.lblTitle.setText("Main");
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddcomputerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddcomputerActionPerformed
        pnlCenter.removeAll();
        pnlCenter.repaint();
        pnlCenter.add(new AddComputer(state)).setVisible(true);
    }//GEN-LAST:event_btnAddcomputerActionPerformed

    private void btnDeletecomputerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletecomputerActionPerformed
        pnlCenter.removeAll();
        pnlCenter.repaint();
        pnlCenter.add(new DeleteComputer(state)).setVisible(true);
    }//GEN-LAST:event_btnDeletecomputerActionPerformed

    private void btnAddpartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddpartActionPerformed
        pnlCenter.removeAll();
        pnlCenter.repaint();
        pnlCenter.add(new AddPart(state)).setVisible(true);
    }//GEN-LAST:event_btnAddpartActionPerformed

    private void btnUpdatepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatepartActionPerformed
        pnlCenter.removeAll();
        pnlCenter.repaint();
        pnlCenter.add(new UpdatePart(state)).setVisible(true);
    }//GEN-LAST:event_btnUpdatepartActionPerformed

    private void btneletepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneletepartActionPerformed
        pnlCenter.removeAll();
        pnlCenter.repaint();
        pnlCenter.add(new DeletePart(state)).setVisible(true);
    }//GEN-LAST:event_btneletepartActionPerformed

    private void btnWarrantyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWarrantyActionPerformed
        pnlCenter.removeAll();
        pnlCenter.repaint();
        pnlCenter.add(new Warranty(state)).setVisible(true);
    }//GEN-LAST:event_btnWarrantyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btnAddcomputer;
    private keeptoo.KButton btnAddpart;
    private keeptoo.KButton btnBack;
    private keeptoo.KButton btnDeletecomputer;
    private keeptoo.KButton btnUpdatepart;
    private keeptoo.KButton btnWarranty;
    private keeptoo.KButton btneletepart;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlLeft;
    // End of variables declaration//GEN-END:variables

    private void setTheme(boolean state) {
        if (state) {
            pnlLeft.setBackground(new Color(99, 100, 100));
            pnlCenter.setBackground(Color.BLACK);

            btnBack.setkBackGroundColor(new Color(99, 100, 100));
            btnBack.setkForeGround(Color.WHITE);
            btnAddcomputer.setkBackGroundColor(new Color(99, 100, 100));
            btnAddcomputer.setForeground(Color.WHITE);
            btnAddcomputer.setkForeGround(Color.WHITE);
            btnDeletecomputer.setkBackGroundColor(new Color(99, 100, 100));
            btnDeletecomputer.setForeground(Color.WHITE);
            btnDeletecomputer.setkForeGround(Color.WHITE);
        } else {
            pnlLeft.setBackground(new Color(230, 230, 230));
            pnlCenter.setBackground(Color.WHITE);

            btnBack.setkBackGroundColor(new Color(230, 230, 230));
            btnBack.setkForeGround(Color.BLACK);
            btnAddcomputer.setkBackGroundColor(new Color(230, 230, 230));
            btnAddcomputer.setkForeGround(Color.BLACK);
            btnDeletecomputer.setkBackGroundColor(new Color(230, 230, 230));
            btnDeletecomputer.setkForeGround(Color.BLACK);          
        }
    }
}
