/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.moderntech.views;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import lk.ijse.moderntech.controler.LoginReportController;
import lk.ijse.moderntech.model.LoginDetailModel;

/**
 *
 * @author Shamal
 */
public class LoginReport extends javax.swing.JInternalFrame {

    boolean state;

    /**
     * Creates new form LoginReport
     */
    public LoginReport(boolean state) {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.state = state;
        loadEmpID();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBack = new javax.swing.JPanel();
        lblEmployeeid = new javax.swing.JLabel();
        cmbEmployeeid = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLogin = new javax.swing.JTable();

        setBorder(null);

        pnlBack.setBackground(new java.awt.Color(255, 255, 255));
        pnlBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEmployeeid.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblEmployeeid.setText("Employee ID :");
        pnlBack.add(lblEmployeeid, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        cmbEmployeeid.setEditable(true);
        cmbEmployeeid.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        cmbEmployeeid.setBorder(null);
        cmbEmployeeid.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbEmployeeidItemStateChanged(evt);
            }
        });
        cmbEmployeeid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEmployeeidActionPerformed(evt);
            }
        });
        pnlBack.add(cmbEmployeeid, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 320, -1));
        pnlBack.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 1280, 10));

        tblLogin.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        tblLogin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Login date and time", "Logout date andtime"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblLogin.setRowHeight(20);
        jScrollPane1.setViewportView(tblLogin);
        if (tblLogin.getColumnModel().getColumnCount() > 0) {
            tblLogin.getColumnModel().getColumn(1).setResizable(false);
        }

        pnlBack.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 1080, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbEmployeeidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEmployeeidActionPerformed
        if (cmbEmployeeid.getSelectedItem() != null) {
            try {
                List<LoginDetailModel> log = new LoginReportController().getLog(cmbEmployeeid.getSelectedItem().toString());

                if (log != null) {
                    DefaultTableModel model = (DefaultTableModel) tblLogin.getModel();
                    model.setRowCount(0);

                    for (LoginDetailModel loginDetailModel : log) {
                        model.addRow(new Object[]{
                            loginDetailModel.getLogin(),
                            loginDetailModel.getLogout()
                        });
                    }
                } else {
                    new InformationBox(new javax.swing.JFrame(), true, "Enter correct ID.").setVisible(true);
                }
            } catch (ClassNotFoundException ex) {
                new ErrorBox(new javax.swing.JFrame(), true, "Class not found exception").setVisible(true);
            } catch (SQLException ex) {
                new ErrorBox(new javax.swing.JFrame(), true, "Sql exception").setVisible(true);
            }

        }
    }//GEN-LAST:event_cmbEmployeeidActionPerformed

    private void cmbEmployeeidItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbEmployeeidItemStateChanged
        if (cmbEmployeeid.getSelectedItem() != null) {
            try {
                List<LoginDetailModel> log = new LoginReportController().getLog(cmbEmployeeid.getSelectedItem().toString());

                if (log != null) {
                    DefaultTableModel model = (DefaultTableModel) tblLogin.getModel();
                    model.setRowCount(0);

                    for (LoginDetailModel loginDetailModel : log) {
                        model.addRow(new Object[]{
                            loginDetailModel.getLogin(),
                            loginDetailModel.getLogout()
                        });
                    }
                } else {
                    new InformationBox(new javax.swing.JFrame(), true, "Enter correct ID.").setVisible(true);
                }
            } catch (ClassNotFoundException ex) {
                new ErrorBox(new javax.swing.JFrame(), true, "Class not found exception").setVisible(true);
            } catch (SQLException ex) {
                new ErrorBox(new javax.swing.JFrame(), true, "Sql exception").setVisible(true);
            }

        }
    }//GEN-LAST:event_cmbEmployeeidItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbEmployeeid;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblEmployeeid;
    private javax.swing.JPanel pnlBack;
    private javax.swing.JTable tblLogin;
    // End of variables declaration//GEN-END:variables

    private void loadEmpID() {
        try {
            List<String> list = new LoginReportController().getEmployee();

            for (String string : list) {
                cmbEmployeeid.addItem(string);
            }

        } catch (ClassNotFoundException ex) {
            new ErrorBox(new javax.swing.JFrame(), true, "Class not found exception").setVisible(true);
        } catch (SQLException ex) {
            new ErrorBox(new javax.swing.JFrame(), true, "Sql exception").setVisible(true);
        }
    }
}
