/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.moderntech.views;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.border.LineBorder;
import lk.ijse.moderntech.controler.mainController;

/**
 *
 * @author Shamal
 */
public class MainIcons extends javax.swing.JInternalFrame {

    Main main;
    boolean state;

    /**
     * Creates new form MainIcons
     */
    public MainIcons(Main main, boolean state) {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.main = main;
        this.state = state;
        setTheme();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlIcons = new javax.swing.JPanel();
        lblBill = new javax.swing.JLabel();
        lblRepair = new javax.swing.JLabel();
        lblPurchase = new javax.swing.JLabel();
        lblStock = new javax.swing.JLabel();
        lblCustomers = new javax.swing.JLabel();
        lblItems = new javax.swing.JLabel();
        lblSupplier = new javax.swing.JLabel();
        lblReports = new javax.swing.JLabel();
        lblDashboard = new javax.swing.JLabel();
        lblSearch = new javax.swing.JLabel();
        lblUsers = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        lblBarcode = new javax.swing.JLabel();
        btnTheme = new keeptoo.KButton();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(1600, 820));

        pnlIcons.setBackground(new java.awt.Color(255, 255, 255));
        pnlIcons.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBill.setFont(new java.awt.Font("Poppins", 0, 36)); // NOI18N
        lblBill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/moderntech/img/icons8_bill_80px_1.png"))); // NOI18N
        lblBill.setText(" Bill");
        lblBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBillMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBillMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBillMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBillMousePressed(evt);
            }
        });
        pnlIcons.add(lblBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 310, 100));

        lblRepair.setFont(new java.awt.Font("Poppins", 0, 36)); // NOI18N
        lblRepair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/moderntech/img/icons8_maintenance_80px_1.png"))); // NOI18N
        lblRepair.setText("Repair");
        lblRepair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRepairMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRepairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRepairMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblRepairMousePressed(evt);
            }
        });
        pnlIcons.add(lblRepair, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 310, 100));

        lblPurchase.setFont(new java.awt.Font("Poppins", 0, 36)); // NOI18N
        lblPurchase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/moderntech/img/icons8_card_in_use_80px_1.png"))); // NOI18N
        lblPurchase.setText("Purchase");
        lblPurchase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPurchaseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPurchaseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPurchaseMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblPurchaseMousePressed(evt);
            }
        });
        pnlIcons.add(lblPurchase, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 110, 310, 100));

        lblStock.setFont(new java.awt.Font("Poppins", 0, 36)); // NOI18N
        lblStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/moderntech/img/icons8_depot_80px.png"))); // NOI18N
        lblStock.setText("Stock");
        lblStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblStockMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblStockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblStockMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblStockMousePressed(evt);
            }
        });
        pnlIcons.add(lblStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 110, 310, 100));

        lblCustomers.setFont(new java.awt.Font("Poppins", 0, 36)); // NOI18N
        lblCustomers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/moderntech/img/icons8_user_80px_1.png"))); // NOI18N
        lblCustomers.setText("Customer");
        lblCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCustomersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCustomersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCustomersMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCustomersMousePressed(evt);
            }
        });
        pnlIcons.add(lblCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 310, 100));

        lblItems.setFont(new java.awt.Font("Poppins", 0, 36)); // NOI18N
        lblItems.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/moderntech/img/icons8_bulleted_list_80px.png"))); // NOI18N
        lblItems.setText("Items");
        lblItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblItemsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblItemsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblItemsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblItemsMousePressed(evt);
            }
        });
        pnlIcons.add(lblItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 310, 100));

        lblSupplier.setFont(new java.awt.Font("Poppins", 0, 36)); // NOI18N
        lblSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/moderntech/img/icons8_supplier_80px_1.png"))); // NOI18N
        lblSupplier.setText("Supplier");
        lblSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSupplierMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSupplierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSupplierMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSupplierMousePressed(evt);
            }
        });
        pnlIcons.add(lblSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 270, 310, 100));

        lblReports.setFont(new java.awt.Font("Poppins", 0, 36)); // NOI18N
        lblReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/moderntech/img/icons8_combo_chart_80px_1.png"))); // NOI18N
        lblReports.setText("Reports");
        lblReports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReportsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblReportsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblReportsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblReportsMousePressed(evt);
            }
        });
        pnlIcons.add(lblReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 270, 310, 100));

        lblDashboard.setFont(new java.awt.Font("Poppins", 0, 36)); // NOI18N
        lblDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/moderntech/img/icons8_speedometer_80px.png"))); // NOI18N
        lblDashboard.setText("Dashboard");
        lblDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDashboardMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblDashboardMousePressed(evt);
            }
        });
        pnlIcons.add(lblDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 420, 310, 100));

        lblSearch.setFont(new java.awt.Font("Poppins", 0, 36)); // NOI18N
        lblSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/moderntech/img/icons8_search_80px.png"))); // NOI18N
        lblSearch.setText("Search");
        lblSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSearchMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSearchMousePressed(evt);
            }
        });
        pnlIcons.add(lblSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 310, 100));

        lblUsers.setFont(new java.awt.Font("Poppins", 0, 36)); // NOI18N
        lblUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/moderntech/img/icons8_groups_80px.png"))); // NOI18N
        lblUsers.setText("Employee");
        lblUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUsersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUsersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUsersMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblUsersMousePressed(evt);
            }
        });
        pnlIcons.add(lblUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 310, 100));

        lblLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/moderntech/img/icons8_logout_rounded_left_30px.png"))); // NOI18N
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
        });
        pnlIcons.add(lblLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 770, -1, -1));

        lblBarcode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/moderntech/img/icons8_barcode_30px.png"))); // NOI18N
        pnlIcons.add(lblBarcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 770, -1, -1));

        btnTheme.setBorder(null);
        btnTheme.setForeground(new java.awt.Color(0, 0, 0));
        btnTheme.setText("Light");
        btnTheme.setkAllowGradient(false);
        btnTheme.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        btnTheme.setkBorderRadius(0);
        btnTheme.setkForeGround(new java.awt.Color(0, 0, 0));
        btnTheme.setkHoverColor(new java.awt.Color(210, 210, 210));
        btnTheme.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemeActionPerformed(evt);
            }
        });
        pnlIcons.add(btnTheme, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 750, 80, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlIcons, javax.swing.GroupLayout.DEFAULT_SIZE, 1591, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlIcons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblBillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBillMouseClicked
        this.dispose();
        main.pnlMain.add(new BillMain(main, state)).setVisible(true);
        main.lblTitle.setText("Bill");
    }//GEN-LAST:event_lblBillMouseClicked

    private void lblBillMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBillMouseEntered
        lblBill.setBorder(new LineBorder(new Color(171, 171, 171), 2));
    }//GEN-LAST:event_lblBillMouseEntered

    private void lblBillMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBillMouseExited
        lblBill.setBorder(BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_lblBillMouseExited

    private void lblBillMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBillMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBillMousePressed

    private void lblRepairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRepairMouseClicked
        this.dispose();
        main.pnlMain.add(new RepairMain(main, state)).setVisible(true);
        main.lblTitle.setText("Repair");
    }//GEN-LAST:event_lblRepairMouseClicked

    private void lblRepairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRepairMouseEntered
        lblRepair.setBorder(new LineBorder(new Color(171, 171, 171), 2));
    }//GEN-LAST:event_lblRepairMouseEntered

    private void lblRepairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRepairMouseExited
        lblRepair.setBorder(BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_lblRepairMouseExited

    private void lblRepairMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRepairMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblRepairMousePressed

    private void lblPurchaseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPurchaseMouseEntered
        lblPurchase.setBorder(new LineBorder(new Color(171, 171, 171), 2));
    }//GEN-LAST:event_lblPurchaseMouseEntered

    private void lblPurchaseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPurchaseMouseExited
        lblPurchase.setBorder(BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_lblPurchaseMouseExited

    private void lblPurchaseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPurchaseMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblPurchaseMousePressed

    private void lblStockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStockMouseEntered
        lblStock.setBorder(new LineBorder(new Color(171, 171, 171), 2));
    }//GEN-LAST:event_lblStockMouseEntered

    private void lblStockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStockMouseExited
        lblStock.setBorder(BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_lblStockMouseExited

    private void lblStockMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStockMousePressed

    }//GEN-LAST:event_lblStockMousePressed

    private void lblCustomersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCustomersMouseEntered
        lblCustomers.setBorder(new LineBorder(new Color(171, 171, 171), 2));
    }//GEN-LAST:event_lblCustomersMouseEntered

    private void lblCustomersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCustomersMouseExited
        lblCustomers.setBorder(BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_lblCustomersMouseExited

    private void lblCustomersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCustomersMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCustomersMousePressed

    private void lblItemsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblItemsMouseEntered
        lblItems.setBorder(new LineBorder(new Color(171, 171, 171), 2));
    }//GEN-LAST:event_lblItemsMouseEntered

    private void lblItemsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblItemsMouseExited
        lblItems.setBorder(BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_lblItemsMouseExited

    private void lblItemsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblItemsMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblItemsMousePressed

    private void lblSupplierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSupplierMouseEntered
        lblSupplier.setBorder(new LineBorder(new Color(171, 171, 171), 2));
    }//GEN-LAST:event_lblSupplierMouseEntered

    private void lblSupplierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSupplierMouseExited
        lblSupplier.setBorder(BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_lblSupplierMouseExited

    private void lblSupplierMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSupplierMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSupplierMousePressed

    private void lblReportsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportsMouseEntered
        lblReports.setBorder(new LineBorder(new Color(171, 171, 171), 2));
    }//GEN-LAST:event_lblReportsMouseEntered

    private void lblReportsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportsMouseExited
        lblReports.setBorder(BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_lblReportsMouseExited

    private void lblReportsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportsMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblReportsMousePressed

    private void lblDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDashboardMouseEntered
        lblDashboard.setBorder(new LineBorder(new Color(171, 171, 171), 2));
    }//GEN-LAST:event_lblDashboardMouseEntered

    private void lblDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDashboardMouseExited
        lblDashboard.setBorder(BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_lblDashboardMouseExited

    private void lblDashboardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDashboardMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDashboardMousePressed

    private void lblUsersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsersMouseEntered
        lblUsers.setBorder(new LineBorder(new Color(171, 171, 171), 2));
    }//GEN-LAST:event_lblUsersMouseEntered

    private void lblUsersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsersMouseExited
        lblUsers.setBorder(BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_lblUsersMouseExited

    private void lblUsersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsersMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblUsersMousePressed

    private void lblPurchaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPurchaseMouseClicked
        this.dispose();
        main.pnlMain.add(new PurchaseMain(main, state)).setVisible(true);
        main.lblTitle.setText("Purchase");
    }//GEN-LAST:event_lblPurchaseMouseClicked

    private void lblStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStockMouseClicked
        this.dispose();
        main.pnlMain.add(new StockMain(main, state)).setVisible(true);
        main.lblTitle.setText("Stock");
    }//GEN-LAST:event_lblStockMouseClicked

    private void lblCustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCustomersMouseClicked
        this.dispose();
        main.pnlMain.add(new CustomerMain(main, state)).setVisible(true);
        main.lblTitle.setText("Customer");
    }//GEN-LAST:event_lblCustomersMouseClicked

    private void lblItemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblItemsMouseClicked
        this.dispose();
        main.pnlMain.add(new ItemsMain(main, state)).setVisible(true);
        main.lblTitle.setText("Items");
    }//GEN-LAST:event_lblItemsMouseClicked

    private void lblSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSupplierMouseClicked
        this.dispose();
        main.pnlMain.add(new SupplierMain(main, state)).setVisible(true);
        main.lblTitle.setText("Supplier");
    }//GEN-LAST:event_lblSupplierMouseClicked

    private void lblReportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportsMouseClicked
        this.dispose();
        main.pnlMain.add(new ReportsMain(main, state)).setVisible(true);
        main.lblTitle.setText("Reports");
    }//GEN-LAST:event_lblReportsMouseClicked

    private void lblUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsersMouseClicked
        this.dispose();
        main.pnlMain.add(new EmployeeMain(main, state)).setVisible(true);
        main.lblTitle.setText("Users");
    }//GEN-LAST:event_lblUsersMouseClicked

    private void lblDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDashboardMouseClicked
        this.dispose();
        main.pnlMain.add(new DashboardMain(main, state)).setVisible(true);
        main.lblTitle.setText("Dashboard");
    }//GEN-LAST:event_lblDashboardMouseClicked

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        try {
            boolean isLogout = new mainController().setLogoutTime(main.empID);
            if (isLogout) {
                main.dispose();
                new LoginScreen().setVisible(true);
            } else {
                new InformationBox(new javax.swing.JFrame(), true, "Can't save logout time. Try again.").setVisible(true);
            }
        } catch (ClassNotFoundException ex) {
            new ErrorBox(new javax.swing.JFrame(), true, "Class not found exception").setVisible(true);
        } catch (SQLException ex) {
            new ErrorBox(new javax.swing.JFrame(), true, "Sql exception").setVisible(true);
        }
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void btnThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemeActionPerformed
        if (btnTheme.getText().equals("Light")) {

            state = true;

        } else if (btnTheme.getText().equals("Dark")) {

            state = false;
        }
        setTheme();
    }//GEN-LAST:event_btnThemeActionPerformed

    private void lblSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchMouseClicked
        this.dispose();
        main.pnlMain.add(new SearchMain(main, state)).setVisible(true);
        main.lblTitle.setText("Search");
    }//GEN-LAST:event_lblSearchMouseClicked

    private void lblSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchMouseEntered
        lblSearch.setBorder(new LineBorder(new Color(171, 171, 171), 2));
    }//GEN-LAST:event_lblSearchMouseEntered

    private void lblSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchMouseExited
        lblSearch.setBorder(BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_lblSearchMouseExited

    private void lblSearchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSearchMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btnTheme;
    private javax.swing.JLabel lblBarcode;
    private javax.swing.JLabel lblBill;
    private javax.swing.JLabel lblCustomers;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblItems;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblPurchase;
    private javax.swing.JLabel lblRepair;
    private javax.swing.JLabel lblReports;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblSupplier;
    private javax.swing.JLabel lblUsers;
    private javax.swing.JPanel pnlIcons;
    // End of variables declaration//GEN-END:variables

    private void setTheme() {
        if (state) {

            btnTheme.setText("Dark");
            btnTheme.setkBackGroundColor(new Color(50, 50, 50));
            btnTheme.setkForeGround(Color.WHITE);
            btnTheme.setForeground(Color.WHITE);

            pnlIcons.setBackground(new Color(50, 50, 50));
            lblBill.setForeground(Color.WHITE);
            lblCustomers.setForeground(Color.WHITE);
            lblDashboard.setForeground(Color.WHITE);
            lblItems.setForeground(Color.WHITE);
            lblPurchase.setForeground(Color.WHITE);
            lblRepair.setForeground(Color.WHITE);
            lblReports.setForeground(Color.WHITE);
            lblStock.setForeground(Color.WHITE);
            lblSupplier.setForeground(Color.WHITE);
            lblUsers.setForeground(Color.WHITE);
            lblSearch.setForeground(Color.WHITE);
        } else {

            btnTheme.setText("Light");
            btnTheme.setkBackGroundColor(Color.white);
            btnTheme.setkForeGround(Color.BLACK);
            btnTheme.setForeground(Color.BLACK);

            pnlIcons.setBackground(Color.WHITE);
            lblBill.setForeground(Color.BLACK);
            lblCustomers.setForeground(Color.BLACK);
            lblDashboard.setForeground(Color.BLACK);
            lblItems.setForeground(Color.BLACK);
            lblPurchase.setForeground(Color.BLACK);
            lblRepair.setForeground(Color.BLACK);
            lblReports.setForeground(Color.BLACK);
            lblStock.setForeground(Color.BLACK);
            lblSupplier.setForeground(Color.BLACK);
            lblUsers.setForeground(Color.BLACK);
            lblSearch.setForeground(Color.BLACK);
        }
    }
}
