/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.moderntech.views;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import lk.ijse.moderntech.controler.ManageSpecController;
import lk.ijse.moderntech.model.SpecModel;

/**
 *
 * @author Shamal
 */
public class ManageSpec extends javax.swing.JDialog {

    /**
     * Creates new form ManageSpec
     */
    public ManageSpec(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setModal(true);
        this.setAlwaysOnTop(true);
        this.setModalityType(ModalityType.APPLICATION_MODAL);
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblValue = new javax.swing.JLabel();
        txtValue = new javax.swing.JTextField();
        lblSpecid = new javax.swing.JLabel();
        cmbPart = new javax.swing.JComboBox<>();
        lblPart = new javax.swing.JLabel();
        txtSpecid = new javax.swing.JTextField();
        btnClear = new keeptoo.KButton();
        btnSave = new keeptoo.KButton();
        btnDelete = new keeptoo.KButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSpec = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblValue.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblValue.setText("Value :");
        jPanel1.add(lblValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, -1, -1));

        txtValue.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        txtValue.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 120, 215)));
        txtValue.setEnabled(false);
        jPanel1.add(txtValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, 320, -1));

        lblSpecid.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblSpecid.setText("Spec ID :");
        jPanel1.add(lblSpecid, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        cmbPart.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbPart.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "processor", "ram", "vga", "motherboard", "hard drive" }));
        jPanel1.add(cmbPart, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 320, 30));

        lblPart.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblPart.setText("Part :");
        jPanel1.add(lblPart, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        txtSpecid.setBackground(new java.awt.Color(240, 240, 240));
        txtSpecid.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        txtSpecid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 120, 215)));
        jPanel1.add(txtSpecid, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 320, -1));

        btnClear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 46, 50)));
        btnClear.setForeground(new java.awt.Color(255, 46, 50));
        btnClear.setText("Clear");
        btnClear.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        btnClear.setkAllowGradient(false);
        btnClear.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        btnClear.setkBorderRadius(0);
        btnClear.setkForeGround(new java.awt.Color(255, 46, 50));
        btnClear.setkHoverColor(new java.awt.Color(255, 46, 50));
        btnClear.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, -1));

        btnSave.setBorder(null);
        btnSave.setText("Save");
        btnSave.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        btnSave.setkAllowGradient(false);
        btnSave.setkBackGroundColor(new java.awt.Color(0, 120, 215));
        btnSave.setkBorderRadius(0);
        btnSave.setkHoverColor(new java.awt.Color(0, 80, 143));
        btnSave.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, -1, -1));

        btnDelete.setBorder(null);
        btnDelete.setText("Delete");
        btnDelete.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        btnDelete.setkAllowGradient(false);
        btnDelete.setkBackGroundColor(new java.awt.Color(231, 84, 78));
        btnDelete.setkBorderRadius(0);
        btnDelete.setkHoverColor(new java.awt.Color(232, 95, 95));
        btnDelete.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, -1, -1));

        tblSpec.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        tblSpec.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Spec ID", "Part", "Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSpec.setRowHeight(20);
        tblSpec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSpecMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSpec);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 1010, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1037, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearAll();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (txtSpecid.getText().trim().length() > 0 && txtValue.getText().trim().length() > 0) {

            SpecModel spec = new SpecModel(
                    txtSpecid.getText(),
                    cmbPart.getSelectedItem().toString(),
                    txtValue.getText()
            );

            try {
                boolean saved = new ManageSpecController().saveSpec(spec);
                if (saved) {
                    new InformationBox(new javax.swing.JFrame(), true, "Saved successfully.").setVisible(true);
                } else {
                    new InformationBox(new javax.swing.JFrame(), true, "Something went wrong, Try again.").setVisible(true);
                }

            } catch (ClassNotFoundException ex) {
                new ErrorBox(new javax.swing.JFrame(), true, "Class not found exception").setVisible(true);
            } catch (SQLException ex) {
                new ErrorBox(new javax.swing.JFrame(), true, "Sql exception").setVisible(true);
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            boolean deleted = new ManageSpecController().deleteSpec(txtSpecid.getText());
            if (deleted) {
                new InformationBox(new javax.swing.JFrame(), true, "Deleted successfully.").setVisible(true);
            } else {
                new InformationBox(new javax.swing.JFrame(), true, "Something went wrong, Try again.").setVisible(true);
            }
        } catch (ClassNotFoundException ex) {
            new ErrorBox(new javax.swing.JFrame(), true, "Class not found exception").setVisible(true);
        } catch (SQLException ex) {
            new ErrorBox(new javax.swing.JFrame(), true, "Sql exception").setVisible(true);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblSpecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSpecMouseClicked
        int row = tblSpec.getSelectedRow();
        txtSpecid.setText(tblSpec.getValueAt(row, 0).toString());
        cmbPart.setSelectedItem(tblSpec.getValueAt(row, 1));
        txtValue.setText(tblSpec.getValueAt(row, 2).toString());
    }//GEN-LAST:event_tblSpecMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageSpec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageSpec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageSpec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageSpec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ManageSpec dialog = new ManageSpec(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btnClear;
    private keeptoo.KButton btnDelete;
    private keeptoo.KButton btnSave;
    private javax.swing.JComboBox<String> cmbPart;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPart;
    private javax.swing.JLabel lblSpecid;
    private javax.swing.JLabel lblValue;
    private javax.swing.JTable tblSpec;
    private javax.swing.JTextField txtSpecid;
    private javax.swing.JTextField txtValue;
    // End of variables declaration//GEN-END:variables

    private void clearAll() {
        txtSpecid.setText("");
        txtValue.setText("");
        cmbPart.setSelectedIndex(0);
    }

    private void loadTable() {
        try {
            List<SpecModel> list = new ManageSpecController().getAllSpecs();
            DefaultTableModel model = (DefaultTableModel) tblSpec.getModel();
            model.setRowCount(0);

            for (SpecModel specModel : list) {
                model.addRow(new Object[]{
                    specModel.getSpec_ID(),
                    specModel.getPart(),
                    specModel.getValue()
                });
            }

        } catch (ClassNotFoundException ex) {
            new ErrorBox(new javax.swing.JFrame(), true, "Class not found exception").setVisible(true);
        } catch (SQLException ex) {
            new ErrorBox(new javax.swing.JFrame(), true, "Sql exception").setVisible(true);
        }
    }
}
