/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.moderntech.views;

import java.awt.Color;

/**
 *
 * @author Shamal
 */
public class ReportsMain extends javax.swing.JInternalFrame {
    Main main;
    boolean state;
    /**
     * Creates new form BillMain
     */
    public ReportsMain(Main main, boolean state) {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.main = main;
        setTheme(state);
        this.state = state;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLeft = new javax.swing.JPanel();
        btnBack = new keeptoo.KButton();
        btnCustomincome = new keeptoo.KButton();
        btnDailyincome = new keeptoo.KButton();
        btnLoginreport = new keeptoo.KButton();
        pnlCenter = new javax.swing.JPanel();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(1600, 820));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLeft.setBackground(new java.awt.Color(230, 230, 230));
        pnlLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setBorder(null);
        btnBack.setForeground(new java.awt.Color(51, 51, 51));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/moderntech/img/icons8_left_arrow_30px.png"))); // NOI18N
        btnBack.setAlignmentY(0.0F);
        btnBack.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        btnBack.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnBack.setIconTextGap(30);
        btnBack.setkAllowGradient(false);
        btnBack.setkAllowTab(true);
        btnBack.setkBackGroundColor(new java.awt.Color(230, 230, 230));
        btnBack.setkBorderRadius(0);
        btnBack.setkForeGround(new java.awt.Color(51, 51, 51));
        btnBack.setkHoverColor(new java.awt.Color(212, 212, 212));
        btnBack.setkSelectedColor(new java.awt.Color(102, 102, 102));
        btnBack.setkStartColor(new java.awt.Color(255, 102, 102));
        btnBack.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        pnlLeft.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 60));

        btnCustomincome.setBorder(null);
        btnCustomincome.setForeground(new java.awt.Color(0, 0, 0));
        btnCustomincome.setText("Custom income");
        btnCustomincome.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnCustomincome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCustomincome.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnCustomincome.setIconTextGap(20);
        btnCustomincome.setkAllowGradient(false);
        btnCustomincome.setkAllowTab(true);
        btnCustomincome.setkBackGroundColor(new java.awt.Color(230, 230, 230));
        btnCustomincome.setkBorderRadius(0);
        btnCustomincome.setkForeGround(new java.awt.Color(0, 0, 0));
        btnCustomincome.setkHoverColor(new java.awt.Color(212, 212, 212));
        btnCustomincome.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btnCustomincome.setkIndicatorColor(new java.awt.Color(0, 120, 215));
        btnCustomincome.setkIndicatorThickness(5);
        btnCustomincome.setkSelectedColor(new java.awt.Color(200, 200, 200));
        btnCustomincome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomincomeActionPerformed(evt);
            }
        });
        pnlLeft.add(btnCustomincome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 290, 70));

        btnDailyincome.setBorder(null);
        btnDailyincome.setForeground(new java.awt.Color(0, 0, 0));
        btnDailyincome.setText("Daily income");
        btnDailyincome.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnDailyincome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDailyincome.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnDailyincome.setIconTextGap(20);
        btnDailyincome.setkAllowGradient(false);
        btnDailyincome.setkAllowTab(true);
        btnDailyincome.setkBackGroundColor(new java.awt.Color(230, 230, 230));
        btnDailyincome.setkBorderRadius(0);
        btnDailyincome.setkForeGround(new java.awt.Color(0, 0, 0));
        btnDailyincome.setkHoverColor(new java.awt.Color(212, 212, 212));
        btnDailyincome.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btnDailyincome.setkIndicatorColor(new java.awt.Color(0, 120, 215));
        btnDailyincome.setkIndicatorThickness(5);
        btnDailyincome.setkSelectedColor(new java.awt.Color(200, 200, 200));
        btnDailyincome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDailyincomeActionPerformed(evt);
            }
        });
        pnlLeft.add(btnDailyincome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 290, 70));

        btnLoginreport.setBorder(null);
        btnLoginreport.setForeground(new java.awt.Color(0, 0, 0));
        btnLoginreport.setText("Login report");
        btnLoginreport.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnLoginreport.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLoginreport.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnLoginreport.setIconTextGap(20);
        btnLoginreport.setkAllowGradient(false);
        btnLoginreport.setkAllowTab(true);
        btnLoginreport.setkBackGroundColor(new java.awt.Color(230, 230, 230));
        btnLoginreport.setkBorderRadius(0);
        btnLoginreport.setkForeGround(new java.awt.Color(0, 0, 0));
        btnLoginreport.setkHoverColor(new java.awt.Color(212, 212, 212));
        btnLoginreport.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btnLoginreport.setkIndicatorColor(new java.awt.Color(0, 120, 215));
        btnLoginreport.setkIndicatorThickness(5);
        btnLoginreport.setkSelectedColor(new java.awt.Color(200, 200, 200));
        btnLoginreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginreportActionPerformed(evt);
            }
        });
        pnlLeft.add(btnLoginreport, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 290, 70));

        getContentPane().add(pnlLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 820));

        pnlCenter.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlCenterLayout = new javax.swing.GroupLayout(pnlCenter);
        pnlCenter.setLayout(pnlCenterLayout);
        pnlCenterLayout.setHorizontalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1310, Short.MAX_VALUE)
        );
        pnlCenterLayout.setVerticalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );

        getContentPane().add(pnlCenter, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 1310, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
        main.pnlMain.removeAll();
        main.pnlMain.repaint();
        main.pnlMain.add(new MainIcons(main, state)).setVisible(true);
        main.lblTitle.setText("Main");
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDailyincomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDailyincomeActionPerformed
        pnlCenter.removeAll();
        pnlCenter.repaint();
        pnlCenter.add(new DailyIncome(state)).setVisible(true);
    }//GEN-LAST:event_btnDailyincomeActionPerformed

    private void btnCustomincomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomincomeActionPerformed
        pnlCenter.removeAll();
        pnlCenter.repaint();
        pnlCenter.add(new CustomIncome(state)).setVisible(true);
    }//GEN-LAST:event_btnCustomincomeActionPerformed

    private void btnLoginreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginreportActionPerformed
        pnlCenter.removeAll();
        pnlCenter.repaint();
        pnlCenter.add(new LoginReport(state)).setVisible(true);
    }//GEN-LAST:event_btnLoginreportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btnBack;
    private keeptoo.KButton btnCustomincome;
    private keeptoo.KButton btnDailyincome;
    private keeptoo.KButton btnLoginreport;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlLeft;
    // End of variables declaration//GEN-END:variables

    private void setTheme(boolean state) {
        if (state) {
            pnlLeft.setBackground(new Color(99, 100, 100));
            pnlCenter.setBackground(Color.BLACK);

            btnBack.setkBackGroundColor(new Color(99, 100, 100));
            btnBack.setkForeGround(Color.WHITE);
        } else {
            pnlLeft.setBackground(new Color(230, 230, 230));
            pnlCenter.setBackground(Color.WHITE);

            btnBack.setkBackGroundColor(new Color(230, 230, 230));
            btnBack.setkForeGround(Color.BLACK);          
        }
    }
}
