/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.moderntech.views;

import java.awt.Color;

/**
 *
 * @author Shamal
 */
public class SupplierMain extends javax.swing.JInternalFrame {

    Main main;
    boolean state;

    /**
     * Creates new form BillMain
     */
    public SupplierMain(Main main, boolean state) {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.main = main;
        setTheme(state);
        this.state = state;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLeft = new javax.swing.JPanel();
        btnBack = new keeptoo.KButton();
        btnAddsupplier = new keeptoo.KButton();
        btnUpdatesupplier = new keeptoo.KButton();
        btndeletesupplier = new keeptoo.KButton();
        pnlCenter = new javax.swing.JPanel();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(1600, 820));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLeft.setBackground(new java.awt.Color(230, 230, 230));
        pnlLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setBorder(null);
        btnBack.setForeground(new java.awt.Color(51, 51, 51));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/moderntech/img/icons8_left_arrow_30px.png"))); // NOI18N
        btnBack.setAlignmentY(0.0F);
        btnBack.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        btnBack.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnBack.setIconTextGap(30);
        btnBack.setkAllowGradient(false);
        btnBack.setkAllowTab(true);
        btnBack.setkBackGroundColor(new java.awt.Color(230, 230, 230));
        btnBack.setkBorderRadius(0);
        btnBack.setkForeGround(new java.awt.Color(51, 51, 51));
        btnBack.setkHoverColor(new java.awt.Color(212, 212, 212));
        btnBack.setkSelectedColor(new java.awt.Color(102, 102, 102));
        btnBack.setkStartColor(new java.awt.Color(255, 102, 102));
        btnBack.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        pnlLeft.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 60));

        btnAddsupplier.setBorder(null);
        btnAddsupplier.setForeground(new java.awt.Color(0, 0, 0));
        btnAddsupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/moderntech/img/icons8_add_30px.png"))); // NOI18N
        btnAddsupplier.setText("Add supplier");
        btnAddsupplier.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAddsupplier.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAddsupplier.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnAddsupplier.setIconTextGap(20);
        btnAddsupplier.setkAllowGradient(false);
        btnAddsupplier.setkAllowTab(true);
        btnAddsupplier.setkBackGroundColor(new java.awt.Color(230, 230, 230));
        btnAddsupplier.setkBorderRadius(0);
        btnAddsupplier.setkForeGround(new java.awt.Color(0, 0, 0));
        btnAddsupplier.setkHoverColor(new java.awt.Color(212, 212, 212));
        btnAddsupplier.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btnAddsupplier.setkIndicatorColor(new java.awt.Color(0, 120, 215));
        btnAddsupplier.setkIndicatorThickness(5);
        btnAddsupplier.setkSelectedColor(new java.awt.Color(200, 200, 200));
        btnAddsupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddsupplierActionPerformed(evt);
            }
        });
        pnlLeft.add(btnAddsupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 290, 70));

        btnUpdatesupplier.setBorder(null);
        btnUpdatesupplier.setForeground(new java.awt.Color(0, 0, 0));
        btnUpdatesupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/moderntech/img/icons8_Update_Left_Rotation_30px.png"))); // NOI18N
        btnUpdatesupplier.setText("Update supplier");
        btnUpdatesupplier.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnUpdatesupplier.setIconTextGap(20);
        btnUpdatesupplier.setkAllowGradient(false);
        btnUpdatesupplier.setkAllowTab(true);
        btnUpdatesupplier.setkBackGroundColor(new java.awt.Color(230, 230, 230));
        btnUpdatesupplier.setkBorderRadius(0);
        btnUpdatesupplier.setkForeGround(new java.awt.Color(0, 0, 0));
        btnUpdatesupplier.setkHoverColor(new java.awt.Color(212, 212, 212));
        btnUpdatesupplier.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btnUpdatesupplier.setkIndicatorColor(new java.awt.Color(0, 120, 215));
        btnUpdatesupplier.setkIndicatorThickness(5);
        btnUpdatesupplier.setkSelectedColor(new java.awt.Color(200, 200, 200));
        btnUpdatesupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatesupplierActionPerformed(evt);
            }
        });
        pnlLeft.add(btnUpdatesupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 290, 70));

        btndeletesupplier.setBorder(null);
        btndeletesupplier.setForeground(new java.awt.Color(0, 0, 0));
        btndeletesupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/moderntech/img/icons8_delete_sign_30px.png"))); // NOI18N
        btndeletesupplier.setText("Delete supplier");
        btndeletesupplier.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btndeletesupplier.setIconTextGap(20);
        btndeletesupplier.setkAllowGradient(false);
        btndeletesupplier.setkAllowTab(true);
        btndeletesupplier.setkBackGroundColor(new java.awt.Color(230, 230, 230));
        btndeletesupplier.setkBorderRadius(0);
        btndeletesupplier.setkForeGround(new java.awt.Color(0, 0, 0));
        btndeletesupplier.setkHoverColor(new java.awt.Color(212, 212, 212));
        btndeletesupplier.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btndeletesupplier.setkIndicatorColor(new java.awt.Color(0, 120, 215));
        btndeletesupplier.setkIndicatorThickness(5);
        btndeletesupplier.setkSelectedColor(new java.awt.Color(200, 200, 200));
        btndeletesupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeletesupplierActionPerformed(evt);
            }
        });
        pnlLeft.add(btndeletesupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 290, 70));

        getContentPane().add(pnlLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 820));

        pnlCenter.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlCenterLayout = new javax.swing.GroupLayout(pnlCenter);
        pnlCenter.setLayout(pnlCenterLayout);
        pnlCenterLayout.setHorizontalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1310, Short.MAX_VALUE)
        );
        pnlCenterLayout.setVerticalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );

        getContentPane().add(pnlCenter, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 1310, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
        main.pnlMain.removeAll();
        main.pnlMain.repaint();
        main.pnlMain.add(new MainIcons(main, state)).setVisible(true);
        main.lblTitle.setText("Main");
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddsupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddsupplierActionPerformed
        pnlCenter.removeAll();
        pnlCenter.repaint();
        pnlCenter.add(new AddSupplier(state)).setVisible(true);
    }//GEN-LAST:event_btnAddsupplierActionPerformed

    private void btnUpdatesupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatesupplierActionPerformed
        pnlCenter.removeAll();
        pnlCenter.repaint();
        pnlCenter.add(new UpdateSupplier(state)).setVisible(true);
    }//GEN-LAST:event_btnUpdatesupplierActionPerformed

    private void btndeletesupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeletesupplierActionPerformed
        pnlCenter.removeAll();
        pnlCenter.repaint();
        pnlCenter.add(new DeleteSupplier(state)).setVisible(true);
    }//GEN-LAST:event_btndeletesupplierActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btnAddsupplier;
    private keeptoo.KButton btnBack;
    private keeptoo.KButton btnUpdatesupplier;
    private keeptoo.KButton btndeletesupplier;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlLeft;
    // End of variables declaration//GEN-END:variables

    private void setTheme(boolean state) {
        if (state) {
            pnlLeft.setBackground(new Color(99, 100, 100));
            pnlCenter.setBackground(Color.BLACK);

            btnBack.setkBackGroundColor(new Color(99, 100, 100));
            btnBack.setkForeGround(Color.WHITE);
            btnAddsupplier.setkBackGroundColor(new Color(99, 100, 100));
            btnAddsupplier.setForeground(Color.WHITE);
            btnAddsupplier.setkForeGround(Color.WHITE);
            btnUpdatesupplier.setkBackGroundColor(new Color(99, 100, 100));
            btnUpdatesupplier.setForeground(Color.WHITE);
            btnUpdatesupplier.setkForeGround(Color.WHITE);
            btndeletesupplier.setkBackGroundColor(new Color(99, 100, 100));
            btndeletesupplier.setForeground(Color.WHITE);
            btndeletesupplier.setkForeGround(Color.WHITE);
        } else {
            pnlLeft.setBackground(new Color(230, 230, 230));
            pnlCenter.setBackground(Color.WHITE);

            btnBack.setkBackGroundColor(new Color(230, 230, 230));
            btnBack.setkForeGround(Color.BLACK);
            btnAddsupplier.setkBackGroundColor(new Color(230, 230, 230));
            btnAddsupplier.setkForeGround(Color.BLACK);
            btnUpdatesupplier.setkBackGroundColor(new Color(230, 230, 230));
            btnUpdatesupplier.setkForeGround(Color.BLACK);
            btndeletesupplier.setkBackGroundColor(new Color(230, 230, 230));
            btndeletesupplier.setkForeGround(Color.BLACK);
        }
    }
}
