/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.moderntech.views;

import java.awt.Color;

/**
 *
 * @author Shamal
 */
public class UpdateComputer extends javax.swing.JInternalFrame {

    boolean state;

    public UpdateComputer(boolean state) {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.state = state;
        setTheam();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBack = new javax.swing.JPanel();
        lblComputerid = new javax.swing.JLabel();
        txtComputerid = new javax.swing.JTextField();
        lblWarranty = new javax.swing.JLabel();
        cmbWarranty = new javax.swing.JComboBox<>();
        lblBrand = new javax.swing.JLabel();
        txtrand = new javax.swing.JTextField();
        lblDescription = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        lblType = new javax.swing.JLabel();
        cmbType = new javax.swing.JComboBox<>();
        lblComputerspecs = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtProcessor = new javax.swing.JComboBox<>();
        lblRam = new javax.swing.JLabel();
        cmbRam = new javax.swing.JComboBox<>();
        lblMotherboard = new javax.swing.JLabel();
        cmbMotherboard = new javax.swing.JComboBox<>();
        cmbVga = new javax.swing.JComboBox<>();
        lblProcessor = new javax.swing.JLabel();
        lblVga = new javax.swing.JLabel();
        lblharddrive = new javax.swing.JLabel();
        cmbharddrive = new javax.swing.JComboBox<>();
        btnClear = new keeptoo.KButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblComputer = new javax.swing.JTable();
        btnUpdate = new keeptoo.KButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(null);

        pnlBack.setBackground(new java.awt.Color(255, 255, 255));
        pnlBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblComputerid.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblComputerid.setText("Computer ID :");
        pnlBack.add(lblComputerid, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        txtComputerid.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        txtComputerid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 120, 215)));
        pnlBack.add(txtComputerid, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 320, -1));

        lblWarranty.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblWarranty.setText("Warranty :");
        pnlBack.add(lblWarranty, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        cmbWarranty.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        cmbWarranty.setBorder(null);
        pnlBack.add(cmbWarranty, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 320, 40));

        lblBrand.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblBrand.setText("Brand :");
        pnlBack.add(lblBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, -1, -1));

        txtrand.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        txtrand.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 120, 215)));
        pnlBack.add(txtrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 90, 320, -1));

        lblDescription.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblDescription.setText("Description :");
        pnlBack.add(lblDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        txtDescription.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        txtDescription.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 120, 215)));
        pnlBack.add(txtDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 830, -1));

        lblType.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblType.setText("Type :");
        pnlBack.add(lblType, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, -1, -1));

        cmbType.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        cmbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desktop", "Laptop" }));
        cmbType.setBorder(null);
        pnlBack.add(cmbType, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 320, 40));

        lblComputerspecs.setFont(new java.awt.Font("Poppins", 0, 36)); // NOI18N
        lblComputerspecs.setText("Computer specs");
        pnlBack.add(lblComputerspecs, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        pnlBack.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 1260, 10));

        txtProcessor.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        txtProcessor.setBorder(null);
        pnlBack.add(txtProcessor, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 320, 40));

        lblRam.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblRam.setText("Ram :");
        pnlBack.add(lblRam, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 320, -1, -1));

        cmbRam.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        cmbRam.setBorder(null);
        pnlBack.add(cmbRam, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 310, 320, 40));

        lblMotherboard.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblMotherboard.setText("Motherboard :");
        pnlBack.add(lblMotherboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, 130, -1));

        cmbMotherboard.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        cmbMotherboard.setBorder(null);
        pnlBack.add(cmbMotherboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 370, 320, 40));

        cmbVga.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        cmbVga.setBorder(null);
        pnlBack.add(cmbVga, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 320, 40));

        lblProcessor.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblProcessor.setText("Processor :");
        pnlBack.add(lblProcessor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));

        lblVga.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblVga.setText("Vga :");
        pnlBack.add(lblVga, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, -1, -1));

        lblharddrive.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblharddrive.setText("Hard drive :");
        pnlBack.add(lblharddrive, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, -1, -1));

        cmbharddrive.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        cmbharddrive.setBorder(null);
        pnlBack.add(cmbharddrive, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 320, 40));

        btnClear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 46, 50)));
        btnClear.setForeground(new java.awt.Color(255, 46, 50));
        btnClear.setText("Clear");
        btnClear.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        btnClear.setkAllowGradient(false);
        btnClear.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        btnClear.setkBorderRadius(0);
        btnClear.setkForeGround(new java.awt.Color(255, 46, 50));
        btnClear.setkHoverColor(new java.awt.Color(255, 46, 50));
        btnClear.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        pnlBack.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 480, -1, -1));

        tblComputer.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        tblComputer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Computer id", "warranty", "Type", "Brand", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblComputer.setRowHeight(20);
        jScrollPane1.setViewportView(tblComputer);

        pnlBack.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 1270, 260));

        btnUpdate.setBorder(null);
        btnUpdate.setText("Update");
        btnUpdate.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        btnUpdate.setkAllowGradient(false);
        btnUpdate.setkBackGroundColor(new java.awt.Color(226, 141, 13));
        btnUpdate.setkBorderRadius(0);
        btnUpdate.setkHoverColor(new java.awt.Color(217, 90, 32));
        btnUpdate.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        pnlBack.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 480, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btnClear;
    private keeptoo.KButton btnUpdate;
    private javax.swing.JComboBox<String> cmbMotherboard;
    private javax.swing.JComboBox<String> cmbRam;
    private javax.swing.JComboBox<String> cmbType;
    private javax.swing.JComboBox<String> cmbVga;
    private javax.swing.JComboBox<String> cmbWarranty;
    private javax.swing.JComboBox<String> cmbharddrive;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblComputerid;
    private javax.swing.JLabel lblComputerspecs;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblMotherboard;
    private javax.swing.JLabel lblProcessor;
    private javax.swing.JLabel lblRam;
    private javax.swing.JLabel lblType;
    private javax.swing.JLabel lblVga;
    private javax.swing.JLabel lblWarranty;
    private javax.swing.JLabel lblharddrive;
    private javax.swing.JPanel pnlBack;
    private javax.swing.JTable tblComputer;
    private javax.swing.JTextField txtComputerid;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JComboBox<String> txtProcessor;
    private javax.swing.JTextField txtrand;
    // End of variables declaration//GEN-END:variables

    private void setTheam() {
        if (state) {
            pnlBack.setBackground(Color.BLACK);
            lblBrand.setForeground(Color.WHITE);
            lblComputerid.setForeground(Color.WHITE);
            lblComputerspecs.setForeground(Color.WHITE);
            lblDescription.setForeground(Color.WHITE);
            lblMotherboard.setForeground(Color.WHITE);
            lblProcessor.setForeground(Color.WHITE);
            lblRam.setForeground(Color.WHITE);
            lblType.setForeground(Color.WHITE);
            lblVga.setForeground(Color.WHITE);
            lblWarranty.setForeground(Color.WHITE);
            lblharddrive.setForeground(Color.WHITE);
            cmbMotherboard.setForeground(Color.WHITE);
            cmbRam.setForeground(Color.WHITE);
            cmbType.setForeground(Color.WHITE);
            cmbVga.setForeground(Color.WHITE);
            cmbWarranty.setForeground(Color.WHITE);
            cmbharddrive.setForeground(Color.WHITE);
            txtComputerid.setForeground(Color.WHITE);
            txtDescription.setForeground(Color.WHITE);
            txtProcessor.setForeground(Color.WHITE);
            txtrand.setForeground(Color.WHITE);
            cmbMotherboard.setBackground(Color.BLACK);
            cmbRam.setBackground(Color.BLACK);
            cmbType.setBackground(Color.BLACK);
            cmbVga.setBackground(Color.BLACK);
            cmbWarranty.setBackground(Color.BLACK);
            cmbharddrive.setBackground(Color.BLACK);
            txtComputerid.setBackground(Color.BLACK);
            txtDescription.setBackground(Color.BLACK);
            txtProcessor.setBackground(Color.BLACK);
            txtrand.setBackground(Color.BLACK);
        } else {

        }
    }
}
