/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.moderntech.views;

import java.awt.Color;
import java.security.NoSuchAlgorithmException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import lk.ijse.moderntech.controler.UpdateLoginDetailController;
import lk.ijse.moderntech.model.UserModel;

/**
 *
 * @author Shamal
 */
public class UpdateLoginDetail extends javax.swing.JInternalFrame {

    boolean state;
    Main main;

    /**
     * Creates new form UpdateLoginDetail
     */
    public UpdateLoginDetail(boolean state, Main main) {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.state = state;
        this.main = main;
        txtEmployeeid.setText(main.empID);
        setTheam();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBack = new javax.swing.JPanel();
        lblEmployeeid = new javax.swing.JLabel();
        txtEmployeeid = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        btnClear = new keeptoo.KButton();
        btnUpdate = new keeptoo.KButton();
        cbShow = new javax.swing.JCheckBox();
        txtPassword = new javax.swing.JPasswordField();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(1310, 820));

        pnlBack.setBackground(new java.awt.Color(255, 255, 255));
        pnlBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEmployeeid.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblEmployeeid.setText("Employee ID :");
        pnlBack.add(lblEmployeeid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        txtEmployeeid.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        txtEmployeeid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 120, 215)));
        txtEmployeeid.setEnabled(false);
        pnlBack.add(txtEmployeeid, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 320, -1));

        lblUsername.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblUsername.setText("User name :");
        pnlBack.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        txtUsername.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        txtUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 120, 215)));
        pnlBack.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 320, -1));

        lblPassword.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblPassword.setText("Password :");
        pnlBack.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, -1, -1));

        btnClear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 46, 50)));
        btnClear.setForeground(new java.awt.Color(255, 46, 50));
        btnClear.setText("Clear");
        btnClear.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        btnClear.setkAllowGradient(false);
        btnClear.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        btnClear.setkBorderRadius(0);
        btnClear.setkForeGround(new java.awt.Color(255, 46, 50));
        btnClear.setkHoverColor(new java.awt.Color(255, 46, 50));
        btnClear.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        pnlBack.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 270, -1, -1));

        btnUpdate.setBorder(null);
        btnUpdate.setText("Update");
        btnUpdate.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        btnUpdate.setkAllowGradient(false);
        btnUpdate.setkBackGroundColor(new java.awt.Color(226, 141, 13));
        btnUpdate.setkBorderRadius(0);
        btnUpdate.setkHoverColor(new java.awt.Color(217, 90, 32));
        btnUpdate.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        pnlBack.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 270, -1, -1));

        cbShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbShowMouseClicked(evt);
            }
        });
        pnlBack.add(cbShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 170, -1, -1));

        txtPassword.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        txtPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 120, 215)));
        pnlBack.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 170, 300, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearAll();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        UserModel user = new UserModel(
                txtUsername.getText(),
                txtPassword.getText()
        );
        try {
            boolean updated = new UpdateLoginDetailController().updateUser(user, txtEmployeeid.getText());
            if(updated){
                new InformationBox(new javax.swing.JFrame(), true, "Updated successfully.").setVisible(true);
            }else{
                new InformationBox(new javax.swing.JFrame(), true, "Something went wrong, Try again.").setVisible(true);
            }
        } catch (ClassNotFoundException ex) {
            new ErrorBox(new javax.swing.JFrame(), true, "Class not found exception").setVisible(true);
        } catch (SQLException ex) {
            new ErrorBox(new javax.swing.JFrame(), true, "Sql exception").setVisible(true);
        } catch (NoSuchAlgorithmException ex) {
            new ErrorBox(new javax.swing.JFrame(), true, "NoSuchAlgorithm exception").setVisible(true);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void cbShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbShowMouseClicked
        if(cbShow.isSelected()){
            txtPassword.setEchoChar((char)0);
        }else{
            txtPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_cbShowMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btnClear;
    private keeptoo.KButton btnUpdate;
    private javax.swing.JCheckBox cbShow;
    private javax.swing.JLabel lblEmployeeid;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlBack;
    private javax.swing.JTextField txtEmployeeid;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private void setTheam() {
        if (state) {
            pnlBack.setBackground(Color.BLACK);
            lblEmployeeid.setForeground(Color.WHITE);
            lblPassword.setForeground(Color.WHITE);
            lblUsername.setForeground(Color.WHITE);
            txtEmployeeid.setForeground(Color.WHITE);
            txtPassword.setForeground(Color.WHITE);
            txtUsername.setForeground(Color.WHITE);
            txtEmployeeid.setBackground(Color.BLACK);
            txtPassword.setBackground(Color.BLACK);
            txtUsername.setBackground(Color.BLACK);

        } else {
        }
    }

    private void clearAll() {
        txtUsername.setText("");
        txtPassword.setText("");
    }
}
