/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.moderntech.views;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import lk.ijse.moderntech.controler.StockController;
import lk.ijse.moderntech.controler.UpdateStockController;
import lk.ijse.moderntech.model.StockModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Shamal
 */
public class UpdateStock extends javax.swing.JInternalFrame {

    boolean state;

    public UpdateStock(boolean state) {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.state = state;
        setTheam();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBack = new javax.swing.JPanel();
        lblStockid = new javax.swing.JLabel();
        txtStockid = new javax.swing.JTextField();
        lblQty = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        btnClear = new keeptoo.KButton();
        btnUpdate = new keeptoo.KButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStock = new javax.swing.JTable();
        lblItemid = new javax.swing.JLabel();
        txtItemid = new javax.swing.JTextField();
        lblnewQTY = new javax.swing.JLabel();
        txtNewqty = new javax.swing.JTextField();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(1310, 820));

        pnlBack.setBackground(new java.awt.Color(255, 255, 255));
        pnlBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblStockid.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblStockid.setText("Stock ID :");
        pnlBack.add(lblStockid, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        txtStockid.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        txtStockid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 120, 215)));
        txtStockid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockidActionPerformed(evt);
            }
        });
        pnlBack.add(txtStockid, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 320, -1));

        lblQty.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblQty.setText("QTY :");
        pnlBack.add(lblQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 50, -1));

        txtQty.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        txtQty.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 120, 215)));
        txtQty.setEnabled(false);
        pnlBack.add(txtQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 320, -1));

        btnClear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 46, 50)));
        btnClear.setForeground(new java.awt.Color(255, 46, 50));
        btnClear.setText("Clear");
        btnClear.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        btnClear.setkAllowGradient(false);
        btnClear.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        btnClear.setkBorderRadius(0);
        btnClear.setkForeGround(new java.awt.Color(255, 46, 50));
        btnClear.setkHoverColor(new java.awt.Color(255, 46, 50));
        btnClear.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        pnlBack.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 200, -1, -1));

        btnUpdate.setBorder(null);
        btnUpdate.setText("Update");
        btnUpdate.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        btnUpdate.setkAllowGradient(false);
        btnUpdate.setkBackGroundColor(new java.awt.Color(226, 141, 13));
        btnUpdate.setkBorderRadius(0);
        btnUpdate.setkHoverColor(new java.awt.Color(217, 90, 32));
        btnUpdate.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        pnlBack.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 200, -1, -1));

        tblStock.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        tblStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stock ID", "ItemID", "Qty", "Buying price", "Profit precentage", "Selling price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblStock.setRowHeight(20);
        tblStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStockMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblStock);

        pnlBack.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 1270, 510));

        lblItemid.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblItemid.setText("Item ID :");
        pnlBack.add(lblItemid, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 70, -1, -1));

        txtItemid.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        txtItemid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 120, 215)));
        txtItemid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemidActionPerformed(evt);
            }
        });
        pnlBack.add(txtItemid, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 70, 320, -1));

        lblnewQTY.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblnewQTY.setText("Newly adding QTY :");
        pnlBack.add(lblnewQTY, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, 180, -1));

        txtNewqty.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        txtNewqty.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 120, 215)));
        txtNewqty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNewqtyKeyReleased(evt);
            }
        });
        pnlBack.add(txtNewqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 130, 320, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearAll();
        loadTable();
    }//GEN-LAST:event_btnClearActionPerformed

    private void tblStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStockMouseClicked
        int row = tblStock.getSelectedRow();
        txtStockid.setText(tblStock.getValueAt(row, 0).toString());
        txtQty.setText(tblStock.getValueAt(row, 2).toString());
        txtItemid.setText(tblStock.getValueAt(row, 1).toString());
    }//GEN-LAST:event_tblStockMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (txtStockid.getText().trim().length() > 0) {
            StockModel stock = new StockModel();
            if (txtItemid.getText().substring(0, 1).equals("P")) {
                stock.setPartID(txtItemid.getText());
            } else if (txtItemid.getText().substring(0, 1).equals("C")) {
                stock.setComputerID(txtItemid.getText());
            }
            stock.setStockID(txtStockid.getText());
            int qty = Integer.valueOf(txtQty.getText());
            int nqty = Integer.valueOf(txtNewqty.getText());
            int newqty = qty + nqty;
            stock.setQTYonhand(String.valueOf(newqty));

            try {
                boolean updated = new UpdateStockController().updateStock(stock);
                if (updated) {
                    new InformationBox(new javax.swing.JFrame(), true, "Updated successfully.").setVisible(true);
                } else {
                    new InformationBox(new javax.swing.JFrame(), true, "Something went wrong, Try again.").setVisible(true);
                }
            } catch (ClassNotFoundException ex) {
                new ErrorBox(new javax.swing.JFrame(), true, "Class not found exception").setVisible(true);
            } catch (SQLException ex) {
                new ErrorBox(new javax.swing.JFrame(), true, "Sql exception").setVisible(true);
            }
        }
        loadTable();
        clearAll();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtItemidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemidActionPerformed
        try {
            StockModel stock = null;
            if (txtItemid.getText().substring(0, 1).equals("P")) {

                stock = new UpdateStockController().getPart(txtItemid.getText());

            } else if (txtItemid.getText().substring(0, 1).equals("C")) {

                stock = new UpdateStockController().getComputer(txtItemid.getText());

            }
            txtStockid.setText(stock.getStockID());
            txtQty.setText(stock.getQTYonhand());

            DefaultTableModel model = (DefaultTableModel) tblStock.getModel();
            model.setRowCount(0);
            String itemID = null;
            if (stock.getComputerID() != null) {
                itemID = stock.getComputerID();
            } else if (stock.getPartID() != null) {
                itemID = stock.getPartID();
            }
            model.addRow(new Object[]{
                stock.getStockID(),
                itemID,
                stock.getQTYonhand(),
                stock.getBuyingPrice(),
                stock.getProfitPrecentage(),
                stock.getSellingPricel()
            });

        } catch (ClassNotFoundException ex) {
            new ErrorBox(new javax.swing.JFrame(), true, "Class not found exception").setVisible(true);
        } catch (SQLException ex) {
            new ErrorBox(new javax.swing.JFrame(), true, "Sql exception").setVisible(true);
        }
    }//GEN-LAST:event_txtItemidActionPerformed

    private void txtStockidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockidActionPerformed
        if (txtStockid.getText().trim().length() > 0) {
            try {
                StockModel stock = new UpdateStockController().getStock(txtStockid.getText());

                DefaultTableModel model = (DefaultTableModel) tblStock.getModel();
                model.setRowCount(0);
                String itemID = null;
                if (stock.getComputerID() != null) {
                    itemID = stock.getComputerID();
                } else if (stock.getPartID() != null) {
                    itemID = stock.getPartID();
                }
                model.addRow(new Object[]{
                    stock.getStockID(),
                    itemID,
                    stock.getQTYonhand(),
                    stock.getBuyingPrice(),
                    stock.getProfitPrecentage(),
                    stock.getSellingPricel()
                });

                txtItemid.setText(tblStock.getValueAt(0, 1).toString());
                txtQty.setText(tblStock.getValueAt(0, 2).toString());
            } catch (ClassNotFoundException ex) {
                new ErrorBox(new javax.swing.JFrame(), true, "Class not found exception").setVisible(true);
            } catch (SQLException ex) {
                new ErrorBox(new javax.swing.JFrame(), true, "Sql exception").setVisible(true);
            }
        }
    }//GEN-LAST:event_txtStockidActionPerformed

    private void txtNewqtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewqtyKeyReleased
        if (!txtNewqty.getText().matches("[0-9]*")) {
            new InformationBox(new javax.swing.JFrame(), true, "Please only enter numbers.").setVisible(true);
            txtNewqty.setText(txtNewqty.getText().substring(0, txtNewqty.getText().length() - 1));
        }
    }//GEN-LAST:event_txtNewqtyKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btnClear;
    private keeptoo.KButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblItemid;
    private javax.swing.JLabel lblQty;
    private javax.swing.JLabel lblStockid;
    private javax.swing.JLabel lblnewQTY;
    private javax.swing.JPanel pnlBack;
    private javax.swing.JTable tblStock;
    private javax.swing.JTextField txtItemid;
    private javax.swing.JTextField txtNewqty;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtStockid;
    // End of variables declaration//GEN-END:variables

    private void setTheam() {
        if (state) {
            pnlBack.setBackground(Color.BLACK);
            lblItemid.setForeground(Color.WHITE);
            lblQty.setForeground(Color.WHITE);
            lblStockid.setForeground(Color.WHITE);
            lblnewQTY.setForeground(Color.WHITE);
            txtItemid.setForeground(Color.WHITE);
            txtNewqty.setForeground(Color.WHITE);
            txtQty.setForeground(Color.WHITE);
            txtStockid.setForeground(Color.WHITE);
            txtItemid.setBackground(Color.WHITE);
            txtNewqty.setBackground(Color.WHITE);
            txtQty.setBackground(Color.WHITE);
            txtStockid.setBackground(Color.WHITE);
        } else {
        }
    }

    private void loadTable() {
        try {
            List<StockModel> list = new UpdateStockController().getAllItems();
            DefaultTableModel model = (DefaultTableModel) tblStock.getModel();
            model.setRowCount(0);

            for (StockModel stockModel : list) {
                String itemID = null;
                if (stockModel.getComputerID() != null) {
                    itemID = stockModel.getComputerID();
                } else if (stockModel.getPartID() != null) {
                    itemID = stockModel.getPartID();
                }
                model.addRow(new Object[]{
                    stockModel.getStockID(),
                    itemID,
                    stockModel.getQTYonhand(),
                    stockModel.getBuyingPrice(),
                    stockModel.getProfitPrecentage(),
                    stockModel.getSellingPricel()
                });
            }
        } catch (ClassNotFoundException ex) {
            new ErrorBox(new javax.swing.JFrame(), true, "Class not found exception").setVisible(true);
        } catch (SQLException ex) {
            new ErrorBox(new javax.swing.JFrame(), true, "Sql exception").setVisible(true);
        }
    }

    private void clearAll() {
        txtItemid.setText("");
        txtNewqty.setText("");
        txtQty.setText("");
        txtStockid.setText("");
    }
}
